"""The risk assessment as a Markdown document people and agents edit.

**The rule that makes an editable generated file safe, borrowed from SP-1**
(`specgen/specification.py`): the structure is regenerated every run, the
judgement is owned by whoever wrote it, and regeneration never overwrites the
second. Without that, the second run silently deletes every probability anybody
set — and it would look like a successful regeneration while doing it.

The split falls exactly where `derived_from` already puts it:

| Regenerated | Preserved |
|---|---|
| the risk text and its evidence | `probability` — Métis never sets one |
| `impact`, from what the observation means | `owner` |
| which tool produced it | `response`, `status`, `notes` |
| the gathered facts and the open questions | any row a person added by hand |

**Hand-added rows survive.** A row whose id is not one this run generated is
carried through untouched. Somebody adding a supplier risk to a requirement's
assessment is doing the thing this file exists for — the eleven categories Métis
cannot see are most of the register — and a regeneration that deleted it would
teach people not to edit the file.

**Why a table.** It is the form both a person and another agent can edit without
a parser: the id is the join key, and a row that loses its shape is reported
rather than dropped, because silently discarding an edited row is the same defect
as overwriting it.

**The table machinery is shared, not owned here.** Cells, scoped section
reads, positional row parsing and the merge itself live in
`metis_mcp/document_table.py`, because the test design document has the same
three problems and a second copy is how the two would start disagreeing about
what `—` means. What stays here is everything domain-shaped: which columns a
person owns, what a carried-over row means, and what this document says about
itself.

**What the document refuses to print.** No overall score (`report.py` says why),
and no verdict while `status` is `incomplete`. An assessment missing required
inputs states what is missing where the conclusion would go — the alternative is
a document that reads as a clean bill because nobody answered.
"""
from __future__ import annotations

from datetime import datetime, timezone

from metis_mcp.document_table import cell as _cell
from metis_mcp.document_table import header as _table_header
from metis_mcp.document_table import (
    merge_rows,
    parse_pairs,
    parse_rows,
    row,
    row_problems,
)
from metis_mcp.risk.inputs import ASKED, GATHERED, INCOMPLETE, inputs_for

BANNER = (
    "<!-- Generated by `metis risk assess`. The **Probability**, **Owner**, "
    "**Response**, **Status** and **Notes** columns are yours: regeneration "
    "preserves them, and preserves any row you add. Everything else is rewritten "
    "from the model each run. -->"
)

#: Columns a person owns. Regeneration reads these back out of the existing file
#: and writes them into the new one.
HUMAN_COLUMNS = ("probability", "owner", "response", "status", "notes")

#: The table's headings and its field names together, so a column added to one
#: cannot go missing from the other. `id` is the join key, read from the first
#: column, so it has no entry in `_FIELDS`.
_COLUMNS = ("ID", "Risk", "Category", "Prob", "Impact", "Owner", "Response",
            "Status", "Notes", "Evidence")
_FIELDS = ("description", "category", "probability", "impact", "owner",
           "response", "status", "notes", "derived_by")
_HEADER, _RULE = _table_header(_COLUMNS)


def build(assessment: str, subject: str, *, gathered: dict | None = None,
          answers: dict | None = None, candidates: list[dict] | None = None,
          completeness: dict | None = None) -> dict:
    """The document's structure, before it is rendered or merged."""
    return {
        "assessment": assessment,
        "subject": subject,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "gathered": dict(gathered or {}),
        "answers": dict(answers or {}),
        "candidates": list(candidates or []),
        "completeness": completeness or {},
    }


def _summarise(value) -> str:
    if isinstance(value, (list, tuple)):
        return f"{len(value)} item(s)" if value else "none"
    if isinstance(value, dict):
        return ", ".join(f"{k}={v}" for k, v in list(value.items())[:4]) or "none"
    if value is True:
        return "yes"
    if value is False:
        return "no"
    return str(value)


def render_markdown(doc: dict) -> str:
    """The document. Deterministic apart from `generated_at`."""
    declared = {i.name: i for i in inputs_for(doc["assessment"])}
    completeness = doc.get("completeness") or {}
    incomplete = completeness.get("status") == INCOMPLETE
    lines: list[str] = [
        BANNER, "",
        f"# Risk assessment — {doc['subject']}", "",
        f"*{doc['assessment']} assessment, generated {doc['generated_at']}.*", "",
    ]

    # The status goes first and says so plainly. Burying "incomplete" below the
    # findings is how an unfinished assessment gets read as a clean one.
    if incomplete:
        missing = completeness.get("missing_required") or []
        lines += [
            "> ## ⚠ Incomplete — do not read this as a risk rating",
            ">",
            f"> {len(missing)} required input(s) have no value: "
            f"**{', '.join(missing)}**.",
            ">",
            "> The risks below are the ones Métis could observe on its own. They",
            "> are not the assessment. A short list here means nobody has",
            "> answered the questions in *Open questions*, not that the risk is low.",
            "",
        ]
    else:
        lines += ["**Complete** — every declared input was supplied.", ""]

    lines += ["## What Métis gathered", "",
              "| Input | Tool | Value | ",
              "|---|---|---|"]
    for name, value in sorted(doc["gathered"].items()):
        item = declared.get(name)
        tool = f"`{item.tool}`" if item and item.tool else "—"
        lines.append(f"| {name} | {tool} | {_cell(_summarise(value))} |")
    if not doc["gathered"]:
        lines.append("| — | — | nothing was gathered |")

    not_gathered = [i for i in declared.values()
                    if i.source == GATHERED and i.name not in doc["gathered"]]
    if not_gathered:
        lines += ["", "**Not gathered**, and therefore not assessed:", ""]
        lines += [f"- `{i.name}` — {i.absent_means}" for i in not_gathered]

    lines += ["", "## Open questions", ""]
    unanswered = [i for i in declared.values()
                  if i.source == ASKED and i.name not in doc["answers"]]
    if unanswered:
        lines += ["Métis cannot derive these. Somebody has to answer them, and "
                  "until they do the assessment is unfinished.", ""]
        for item in unanswered:
            flag = "**required**" if item.required else "optional"
            lines += [f"### {item.name} ({flag})", "",
                      f"> {item.question}", "",
                      f"*Decides:* {item.why}.  ",
                      f"*Absent means:* {item.absent_means}.", ""]
    else:
        lines += ["All answered.", ""]

    if doc["answers"]:
        lines += ["### Answers on record", "",
                  "| Question | Answer |", "|---|---|"]
        lines += [f"| {name} | {_cell(_summarise(value))} |"
                  for name, value in sorted(doc["answers"].items())]
        lines.append("")

    lines += ["## Risks", "",
              "`Prob` is yours to set — Métis observed these and does not "
              "forecast. `Impact` is derived from what the observation means and "
              "is rewritten each run.", "",
              _HEADER, _RULE]
    for risk in doc["candidates"]:
        lines.append(row([risk.get("id")]
                         + [risk.get(f) for f in _FIELDS[:-1]]
                         + [risk.get("derived_by") or risk.get("derived_from")]))
    if not doc["candidates"]:
        lines.append(row(["\u2014", "no risk was observed from the gathered facts"]
                         + [None] * (len(_COLUMNS) - 2)))

    lines += [
        "", "## How to read this", "",
        "- **No overall score is computed.** A 5x5 exposure is an ordinal rank, "
        "the register holds two kinds of claim, and a model-derived risk has no "
        "probability until somebody sets one.",
        "- **`derived_from: model` means Métis observed a gap**, not that it "
        "forecast a failure. Rating one makes the rating yours.",
        "- **Coverage is not correctness** (C-11). A behaviour can be fully "
        "covered and currently failing.",
        "- Rows you add are preserved. So are your edits to the five columns "
        "named at the top of this file.",
        "",
    ]
    return "\n".join(lines) + "\n"


#: The heading the risk table lives under, and the one that ends it.
_RISKS_HEADING = "## Risks"
_ENDS_RISKS = "## How to read this"


def parse(text: str) -> dict[str, dict]:
    """The risk rows out of an existing document, keyed by id.

    Read by position, and scoped to `## Risks` deliberately -- this document
    holds three pipe-delimited tables and reading them as one turned the
    three-column *gathered facts* table into six malformed risk rows. A row that
    has lost its shape is skipped and named by `parse_problems`, never silently
    dropped: a discarded edit is the same defect as an overwritten one.
    """
    return parse_rows(text, heading=_RISKS_HEADING, ends=(_ENDS_RISKS,),
                      columns=_FIELDS)


#: The heading the answers table lives under, and the one that ends it.
_ANSWERS_HEADING = "### Answers on record"
_ENDS_ANSWERS = "## Risks"

def parse_answers(text: str) -> dict[str, str]:
    """The answered questions out of an existing document.

    **Why this exists.** `render_markdown` has always written this section and
    nothing ever read it back. So the one route a person had for answering an
    open question -- editing the document the workflow tells them to edit, the
    same way they edit the probability column beside it -- lost the answer on the
    next run.

    The consequence was not a lost edit, it was a constant: every assessment
    reported `incomplete` for ever, because the required `ASKED` inputs could
    never be supplied through any surface. That is the precise outcome
    `risk/inputs.py` exists to prevent -- a status that cannot change is one
    readers learn to skip, and it is the same word that has to carry a genuinely
    unfinished assessment when one turns up.

    Answers are read as text, deliberately. Nothing here coerces `high` into a
    rating: converting an answer into a probability is a person's judgement and
    `steps/02-ask.md` requires the converter to be named.
    """
    return parse_pairs(text, heading=_ANSWERS_HEADING, ends=(_ENDS_ANSWERS,),
                       furniture=("Question",))


def parse_problems(text: str) -> list[str]:
    """Rows inside the risk table that could not be read."""
    return row_problems(text, heading=_RISKS_HEADING, ends=(_ENDS_RISKS,),
                        columns=_FIELDS)


def merge(doc: dict, existing: str) -> dict:
    """`doc` with the human columns, hand-added rows and answers carried over.

    The whole point of the module. Returns a NEW document — the generated
    structure, with every column a person owns restored from the file that was
    already there, and every row this run did not produce appended untouched.

    **Answers carry the same way the columns do.** They were the one human-owned
    part of this file that regeneration dropped, which made the `ASKED` half of
    every assessment unanswerable through any surface. An answer this run
    supplied wins over the one already in the file — a fresh acceptance is newer
    than the record of the last one — and everything the run did not mention is
    kept.
    """
    if not existing.strip():
        return doc

    merged, leftover = merge_rows(doc["candidates"], parse(existing),
                                  human_columns=HUMAN_COLUMNS)

    # Whatever is left was not generated by this run: rows somebody added, or
    # rows for a fact that is no longer true. Both are carried through -- Métis
    # deciding a person's row is obsolete is not a call it can make.
    carried = [{**prior, "derived_from": "authored",
                "derived_by": prior.get("derived_by") or "hand-added"}
               for prior in leftover]

    out = dict(doc)
    out["candidates"] = merged + carried
    out["carried_over"] = [r["id"] for r in carried]
    out["answers"] = {**parse_answers(existing), **doc["answers"]}
    return out
