"""The analysis as a Markdown document people and agents edit.

Same rule as `risk/document.py` and `design/document.py`, and the same shared
machinery underneath (`metis_mcp/document_table.py`): the structure is
regenerated every run, the judgement belongs to whoever wrote it, and
regeneration never overwrites the second.

**What a person owns here is the answer and the decision.** A gap Métis found is
regenerated; whether it has been closed, who owns closing it, and what was
decided are columns nobody but a person writes. A hand-added gap survives
untouched -- an analyst seeing something none of the four readers can is the
whole reason this file is editable.

**The verdict goes above the gaps, and it says which reading it is.** `ready`
means the claim can be represented honestly at Quarantine, carrying every
reported gap with it. It does not mean the claim is good, and the banner says so
in those words -- because "ready" is exactly the sort of word a reader
generalises.
"""
from __future__ import annotations

from datetime import datetime, timezone

from metis_mcp.analysis.gaps import ASPECTS, NOT_READY
from metis_mcp.document_table import header, merge_rows, parse_rows, row, row_problems

BANNER = (
    "<!-- Generated by `metis intent review`. The **Closed**, **Owner** and "
    "**Notes** columns are yours: regeneration preserves them, and preserves any "
    "row you add. Everything else is rewritten from the four readers each run. -->"
)

#: Columns a person owns.
HUMAN_COLUMNS = ("closed", "owner", "notes")

_COLUMNS = ("ID", "Aspect", "Subject", "What is missing", "Closes with",
            "Blocks import", "Closed", "Owner", "Notes")
_FIELDS = ("aspect", "subject", "what", "closes_with", "blocks_import",
           "closed", "owner", "notes")
_HEADER, _RULE = header(_COLUMNS)

_GAPS_HEADING = "## Gaps"
_ENDS_GAPS = ("## How to read this",)


def _gap_id(gap: dict, index: int) -> str:
    """A stable id for one gap, derived from what it is about.

    Content-derived for the reason `design.builders.row_id` gives: an id that
    counted rows off would renumber the moment a reader found one more, moving
    every recorded answer onto the wrong gap.
    """
    import hashlib

    material = f"{gap.get('aspect')}␟{gap.get('subject')}␟{gap.get('what')}"
    return f"gap-{hashlib.sha256(material.encode()).hexdigest()[:8]}"


def build(subject: str, analysis: dict) -> dict:
    """The document's structure, before it is rendered or merged."""
    rows = []
    for index, gap in enumerate(analysis.get("gaps") or []):
        rows.append({**gap, "id": _gap_id(gap, index)})
    return {
        "subject": subject,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "status": analysis.get("status"),
        "counts": analysis.get("counts") or {},
        "subjects": analysis.get("subjects") or [],
        "blocking": analysis.get("blocking") or [],
        "means": analysis.get("means", ""),
        "gaps": rows,
    }


def render_markdown(doc: dict) -> str:
    """The document. Deterministic apart from `generated_at`."""
    lines = [
        BANNER, "",
        f"# Intent review — {doc['subject']}", "",
        f"*Intent review generated {doc['generated_at']}.*", "",
    ]

    if doc.get("status") == NOT_READY:
        lines += [
            "> ## ⛔ Not ready to import",
            ">",
            f"> {len(doc['blocking'])} gap(s) mean this claim cannot be "
            f"represented honestly in the graph.",
            ">",
        ] + [f"> - {text}" for text in doc["blocking"]] + [""]
    else:
        lines += [
            "> ## ✅ Ready to import — which is not the same as ready to build",
            ">",
            "> This can be landed at `Quarantine`, carrying every gap below with",
            "> it. **Nobody has agreed with it.** A person decides at G1 (S-4),",
            "> and the gaps below are what they should be looking at.",
            "",
        ]

    lines += ["## What was read", "", "| Subject | Statement | Specifications | Criteria claimed |",
              "|---|---|---|---|"]
    for entry in doc["subjects"]:
        lines.append(row([entry.get("id"), entry.get("statement"),
                          entry.get("specifications"),
                          entry.get("criteria_claimed")]))
    if not doc["subjects"]:
        lines.append(row(["—", "no claim was found in this document", None, None]))

    lines += ["",
              "A claimed acceptance criterion is **counted and never trusted** "
              "into an `AcceptanceCriterion` node. A criterion asserted by the "
              "document that raised the requirement is not independent evidence "
              "of it (S-13).", ""]

    lines += ["## Gaps by aspect", "", "| Aspect | Found | Sees what the others cannot |",
              "|---|---|---|"]
    for aspect in ASPECTS:
        lines.append(row([aspect, doc["counts"].get(aspect, 0),
                          _ASPECT_MEANS[aspect]]))

    lines += ["", _GAPS_HEADING, "",
              "`Closes with` names the skill or tool that closes each. A gap "
              "with no closer would be a complaint.", "",
              _HEADER, _RULE]
    for gap in doc["gaps"]:
        lines.append(row([gap.get("id")] + [gap.get(f) for f in _FIELDS]))
    if not doc["gaps"]:
        lines.append(row(["—", "no gap was found by any of the four readers"]
                         + [None] * (len(_COLUMNS) - 2)))

    lines += [
        "", "## How to read this", "",
        "- **`ready` means representable, not agreed.** It lands at "
        "`Quarantine` and a person decides at G1 (S-4).",
        "- **A reported gap is not a defect in the claim.** \"Nobody has said "
        "which environments exist\" is a fact about the organisation.",
        "- **No readiness figure is computed.** The four aspects are not "
        "commensurable, and averaging them would let a missing statement hide "
        "behind a missing environment list.",
        "- Rows you add are preserved. So are your edits to Closed, Owner and "
        "Notes.",
        "",
    ]
    return "\n".join(lines) + "\n"


_ASPECT_MEANS = {
    "intent": "whether there is a need here at all, and whether anybody said "
              "how it behaves",
    "requirement": "whether the wording can be satisfied twice the same way",
    "design": "whether anything could ever test it, whatever gets built",
    "risk": "whether anybody has said what being wrong costs",
    "consumer": "who reads what this produces — a report and an integration "
                "are tested differently, and nothing else notices",
}


def parse(text: str) -> dict[str, dict]:
    """The gap rows out of an existing document, keyed by id."""
    return parse_rows(text, heading=_GAPS_HEADING, ends=_ENDS_GAPS,
                      columns=_FIELDS)


def parse_problems(text: str) -> list[str]:
    """Gap rows that could not be read. Reported, never dropped."""
    return row_problems(text, heading=_GAPS_HEADING, ends=_ENDS_GAPS,
                        columns=_FIELDS)


def merge(doc: dict, existing: str) -> dict:
    """`doc` with the human columns and hand-added gaps carried over.

    A gap somebody added is a gap none of the four readers could see, which is
    the case this file is editable for. Deleting it on regeneration would teach
    analysts not to write in it.
    """
    if not existing.strip():
        return doc

    merged, leftover = merge_rows(doc["gaps"], parse(existing),
                                  human_columns=HUMAN_COLUMNS)
    carried = [{**prior, "aspect": prior.get("aspect") or "analyst",
                "closes_with": prior.get("closes_with") or "hand-added"}
               for prior in leftover]

    out = dict(doc)
    out["gaps"] = merged + carried
    out["carried_over"] = [str(prior.get("id")) for prior in carried]
    return out
