"""
The client agents are a view, not a second source (§9.5, N-8).

**They had drifted completely.** All five agents under `.github/agents/` declared
MCP tools — `metis_get_context`, `metis_get_traceability`, `metis_check_coverage`
and nine more — and **not one existed**: twelve referenced, seven exposed, zero
overlap. Three of the six skills they documented had been deleted. The endpoint
was still `https://REPLACE-metis-host.example.com/mcp`.

`test_skills.py` has a guard for exactly this and could not see it, for two
reasons worth stating because they are the general lesson:

  * it scans `plugins/metis/skills/` only, and the agents are a **second surface**
    outside that path;
  * it checks a **hardcoded list of seven dead names**, so the five newer dead
    names would have passed even inside `skills/`.

So the tests below compare against what the code *actually exposes*, never
against a list someone has to remember to update.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

from metis_mcp.agent_generator import (
    AGENT_TARGETS, AGENTS, PLUGIN_AGENTS, exposed_tools, generate,
    read_skills, stale_agents,
)
from metis_mcp.workflow.stages import WORKFLOWS

_DECLARED = re.compile(r"^tools:\n((?:- .+\n)+)", re.M)


#: The router is an agent with no skill behind it — it is generated by
#: `workflow.routing.write_router`, not by `agent_generator`. It lived only in
#: the plugin surface, and these tests used to scan `.github/agents/`, so it was
#: never in view. With one surface it is, and every test below has to say
#: whether it means "the skill agents" or "every agent file".
ROUTER = "metis.agent.md"


def _agent_files(include_router: bool = False):
    return sorted(p for p in AGENTS.glob("*.agent.md")
                  if include_router or p.name != ROUTER)


def _agent_skills():
    """The skills that get an agent: parents only.

    A specialist is a skill its PARENT routes to, and gets no agent of its own —
    otherwise it appears in a client's agent list as a peer of the skill that
    owns it, and the nesting that expresses ownership is flattened away.
    """
    return [s for s in read_skills() if not s.parent]


def _declared_tools(text: str) -> list[str]:
    block = _DECLARED.search(text)
    return ([line[2:].strip() for line in block.group(1).splitlines()]
            if block else [])


def test_every_tool_an_agent_declares_is_one_the_server_exposes():
    """Compared against `server.py` itself, so this cannot go stale.

    A hardcoded dead-list is what let twelve phantom tools survive: it only ever
    catches the names someone thought to write down.
    """
    real = set(exposed_tools())
    assert real, "no tools parsed from server.py — the parser is broken, not the agents"

    phantom = []
    for path in _agent_files():
        for tool in _declared_tools(path.read_text()):
            if tool not in real:
                phantom.append(f"{path.name}:{tool}")
    assert not phantom, (
        f"these declare tools the server does not expose: {', '.join(sorted(phantom))}. "
        f"Real surface: {', '.join(sorted(real))}")


def test_no_agent_mentions_a_v1_tool_name_anywhere_in_its_body():
    """Not just the frontmatter. Prose telling a user to "call
    `metis_mine_requirements`" fails exactly as hard as a declaration."""
    real = set(exposed_tools())
    offenders = []
    for path in _agent_files():
        for name in set(re.findall(r"\bmetis_[a-z_]+\b", path.read_text())):
            if name == "metis_mcp" or name in real:
                continue
            offenders.append(f"{path.name}:{name}")
    assert not offenders, (
        f"v1 tool names still referenced: {', '.join(sorted(offenders))}")


def test_every_agent_names_a_skill_that_exists():
    """Three agents documented skills that had been deleted."""
    names = {s.name for s in _agent_skills()}
    assert names, "no skills found"
    for path in _agent_files():
        assert path.name.replace(".agent.md", "") in names, (
            f"{path.name} has no corresponding skill")


def test_every_parent_skill_has_an_agent():
    """The other direction. `metis-model-build` existed with no agent at all, so
    the one workflow that can actually run end to end was unreachable."""
    for skill in _agent_skills():
        assert (AGENTS / f"{skill.name}.agent.md").exists(), (
            f"{skill.name} has no agent")


def test_no_specialist_has_an_agent_of_its_own():
    """The complement, and the reason the split exists. Seven specialists each
    had an agent file, so a client's agent list showed `metis-risk-manager` and
    its three specialists as four peers."""
    for skill in read_skills():
        if not skill.parent:
            continue
        assert not (AGENTS / f"{skill.name}.agent.md").exists(), (
            f"{skill.name} is a specialist and must not have its own agent — "
            f"its parent routes to it")


def test_a_parent_agent_names_the_specialists_it_routes_to():
    """A specialist with no agent is only reachable if its parent names it. This
    is the half that makes the removal safe rather than a deletion."""
    children: dict[str, list[str]] = {}
    for skill in read_skills():
        if skill.parent:
            children.setdefault(skill.parent, []).append(skill.name)
    assert children, "no specialists found — this test would pass vacuously"

    by_directory = {s.directory.name: s for s in _agent_skills() if s.directory}
    for parent_directory, names in children.items():
        parent = by_directory.get(parent_directory)
        assert parent, f"{parent_directory} owns specialists but is not a skill"
        text = (AGENTS / f"{parent.name}.agent.md").read_text()
        for name in names:
            assert name in text, f"{parent.name}'s agent does not route to {name}"


def test_the_checked_in_agents_match_the_generator():
    """Same discipline as `test_ontology.py` asserting the schema matches
    `labels.py`: a generated artefact that has been hand-edited is a second
    source of truth, which is what drifted in the first place."""
    for filename, expected in generate().items():
        path = AGENTS / filename
        assert path.exists(), f"{filename} is missing — regenerate"
        assert path.read_text() == expected, (
            f"{filename} differs from the generator. Do not hand-edit; "
            f"run metis_mcp.agent_generator.write()")


def test_no_stale_agent_survives_a_regeneration():
    assert {p.name for p in _agent_files()} == set(generate()), (
        "an agent exists that the generator does not produce — a deleted skill "
        "leaves its agent behind unless the stale one is removed")


def test_the_placeholder_endpoint_is_gone():
    """`mcp_server: https://REPLACE-metis-host.example.com/mcp` shipped in
    `spec-aware.agent.md` — a fake host nobody replaced."""
    for path in _agent_files():
        assert "REPLACE-" not in path.read_text(), f"{path.name} has a placeholder"


def test_agents_state_what_the_build_cannot_do():
    """An agent advertising a capability it lacks fails in front of a user
    mid-task. The absent ones are named rather than quietly omitted."""
    for path in _agent_files():
        text = path.read_text()
        assert "does not have" in text
        for absent in ("impact analysis", "traceability", "read-only"):
            assert absent in text, f"{path.name} does not mention {absent}"


def test_the_router_lists_every_workflow():
    """**Changed, and the change is the point.** This used to require EVERY agent
    to name EVERY workflow, which made the genericness a rule rather than an
    oversight: a coverage-report agent told its reader about model-build and
    spec-writeback identically to every other agent.

    Listing all five is the ROUTER's job — choosing between them is what it is
    for. An agent's job is its own scope.
    """
    router = PLUGIN_AGENTS / "metis.agent.md"
    text = router.read_text()
    for code in WORKFLOWS:
        assert code in text, f"the router omits workflow {code}"


def test_an_agent_names_its_own_workflow_and_not_the_others():
    """A skill declares `workflow:` in its frontmatter, or drives none."""
    from metis_mcp.agent_generator import read_skills

    by_name = {s.name: s for s in read_skills()}
    for path in _agent_files():
        skill = by_name.get(path.name[:-len(".agent.md")])
        if skill is None or not skill.workflow:
            continue
        body = path.read_text().split("## Doing the work", 1)[1]
        body = body.split("## ", 1)[0]
        assert skill.workflow in body, (
            f"{path.name} does not name its own workflow {skill.workflow}")
        for other in WORKFLOWS:
            if other != skill.workflow:
                assert other not in body, (
                    f"{path.name} drives {skill.workflow} and also names "
                    f"{other} — that is the genericness this replaced")


def test_no_two_agents_are_the_same_document():
    """**The test whose absence let nine agents be one agent.**

    Twelve tests asserted consistency and existence; none asserted difference. So
    97-line files with 93 byte-identical lines passed every check for as long as
    they existed. Distinctness is the property an agent surface has to have — if
    two agents are interchangeable, one of them is not carrying its own scope.
    """
    from metis_mcp.agent_generator import generate

    agents = generate()
    seen: dict[str, str] = {}
    for name, content in sorted(agents.items()):
        body = "\n".join(l for l in content.splitlines()
                          if not l.startswith(("name:", "description:", "# ")))
        assert body not in seen, f"{name} is byte-identical to {seen[body]}"
        seen[body] = name

    # And the sharper form: two agents must not have the same permissions.
    tools = {}
    for name, content in sorted(agents.items()):
        block = _DECLARED.search(content)
        declared = frozenset(block.group(1).split()) if block else frozenset()
        assert declared not in tools, (
            f"{name} and {tools[declared]} declare identical tool sets — one of "
            f"them is not scoped to what its skill needs")
        tools[declared] = name


# --------------------------------------------------------------------------
# Every agent surface, not just the one somebody remembered
# --------------------------------------------------------------------------

def test_no_agent_surface_carries_a_file_no_skill_produces():
    """The rot this closes was real and invisible to both existing tests.

    `plugins/metis/agents/` held four agents for skills that had been deleted,
    naming twelve MCP tools the server does not expose, and linking to a
    `metis-onboarding/SKILL.md` that no longer exists. `test_skills.py` scans
    `skills/` and the router; this file scanned `.github/agents/`. The plugin's
    own agent directory was a third surface, generated by nothing and checked by
    nothing — while every file in it carried a "GENERATED … do not hand-edit"
    banner.
    """
    for target in AGENT_TARGETS:
        assert stale_agents(target) == [], (
            f"{target} carries agent file(s) no live skill produces: "
            f"{[p.name for p in stale_agents(target)]}. Regenerate with "
            f"agent_generator.write()")


def test_there_is_exactly_one_agent_surface():
    """**This replaces two tests that existed only because there were two.**

    `.github/agents/` and `plugins/metis/agents/` held byte-identical files, so
    every agent was in the repository twice and two guards were needed to assert
    the copies agreed. Agents ship through the marketplace plugin now, which
    makes the plugin the one place they live — and a duplicate cannot disagree
    with itself if it does not exist.
    """
    assert AGENT_TARGETS == (PLUGIN_AGENTS,), (
        "a second agent surface is back — it will be regenerated out of step "
        "with this one, which is what the duplication cost last time")
    assert not (PLUGIN_AGENTS.parent.parent.parent / ".github" / "agents").exists(), (
        ".github/agents/ is back and duplicates the plugin surface")


def test_the_generated_agents_match_the_generator_exactly():
    """One generator, one content, one place."""
    for filename, content in generate().items():
        assert (PLUGIN_AGENTS / filename).read_text() == content, (
            f"{filename} has drifted from the generator")


if __name__ == "__main__":
    tests = [v for k, v in list(globals().items()) if k.startswith("test_")]
    failures = 0
    for t in tests:
        try:
            t()
            print(f"PASS {t.__name__}")
        except AssertionError as e:
            failures += 1
            print(f"FAIL {t.__name__}: {e}")
        except Exception as e:                                    # noqa: BLE001
            failures += 1
            print(f"ERROR {t.__name__}: {type(e).__name__}: {e}")
    print(f"\n{len(tests) - failures}/{len(tests)} passed")
    sys.exit(1 if failures else 0)
