"""
Generate the client agent files from the skills and the real MCP surface.

**The agents were hand-maintained and drifted completely.** Every one of the five
under `.github/agents/` declared MCP tools — `metis_get_context`,
`metis_get_traceability`, `metis_check_coverage` and nine more — and **not one of
them exists**: twelve names referenced, seven exposed, zero overlap. Three of the
six skills they documented had been deleted. The generator that was supposed to
keep them honest went away with the v1 engine, so nothing regenerated and nothing
noticed.

This restores it, with the property that matters: an agent is a **view** over
things that are checked elsewhere, never a second place to state them.

  * the tool list comes from `server.py`'s actual `@mcp.tool()` functions
  * the skills come from `plugins/metis/skills/*/SKILL.md` frontmatter
  * the workflows come from `workflow.stages.WORKFLOWS`

So an agent cannot advertise a tool the server does not expose, or a skill that
does not exist, without this file being wrong -- and `test_agents.py` asserts the
checked-in files match what this produces, the same way `test_ontology.py`
asserts the schema matches `labels.py`.

**Tools are named, not invented.** Where a capability an old agent claimed has no
implementation -- impact analysis, traceability, explain-decision -- the agent
says so plainly rather than listing a tool that will fail on first call. An agent
that advertises what it cannot do is worse than one that admits a gap, because
the failure arrives in front of a user mid-task.
"""
from __future__ import annotations

import ast
import re
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
SKILLS = REPO / "plugins" / "metis" / "skills"
# The Claude Code plugin's own agent surface, beside the router it already holds.
#
# **It was a third surface, generated by nothing and checked by nothing**, and it
# had rotted exactly as `test_agents.py`'s docstring predicts: four agents for
# skills that no longer exist, naming twelve MCP tools of which the server
# exposes none, and linking to a `metis-onboarding/SKILL.md` that is gone. Each
# file carried the "GENERATED ... do not hand-edit" banner while no generator
# had written to this directory in a long time.
PLUGIN_AGENTS = REPO / "plugins" / "metis" / "agents"

# **One target, and it is the plugin.** There was a second — `.github/agents/`,
# for Copilot — holding byte-identical files, so every agent existed twice in the
# repository and two tests were needed to assert the copies agreed. Agents are
# distributed through the marketplace plugin now, for both clients, which makes
# the plugin the single place they live and deletes the class of bug where one
# surface is regenerated and the other is not.
AGENT_TARGETS = (PLUGIN_AGENTS,)
AGENTS = PLUGIN_AGENTS      # back-compat for callers that imported the old name

HEADER = ("<!-- GENERATED by metis_mcp/agent_generator.py from the skills' own "
          "frontmatter, the workflow registry, and server.py's real tool list. "
          "Do not hand-edit: regenerate, or the clients drift. -->")

_FRONTMATTER = re.compile(r"^---\n(.*?)\n---", re.S)


@dataclass(frozen=True)
class Skill:
    """One skill's frontmatter — everything a skill contributes to its agent.

    **`workflow` and `tools` are the two joins that did not exist.** Nine skills
    and five workflows were connected only by a sentence inside a SKILL.md, and
    every agent was handed every tool, so nine agents came out 93 lines identical.
    Declaring both here means a skill states its own scope beside the prose that
    explains it, and the generator has something per-skill to emit.

    Both are optional and both fail open. `workflow=""` is the honest answer for
    the four skills that drive none -- they wrap a stage, a tool, an intake or a
    gate. `tools=()` means "everything the server exposes", which is what every
    agent got before this existed, so a skill that has not been migrated behaves
    exactly as it did.
    """

    name: str
    description: str
    workflow: str = ""
    tools: tuple[str, ...] = ()
    # Modules whose docstring is worth putting beside this skill. See
    # `knowledge_gen`: the docstring stays the source of truth and the fragment
    # is generated, so the two cannot drift.
    knowledge_from: tuple[str, ...] = ()
    # Where the skill lives. Needed because a specialist sits one level deeper
    # (`<parent>/specialists/<name>/`) while its NAME stays flat — nesting is
    # ownership, not addressing, so discovery and the agent surface see a peer.
    directory: Path | None = None
    parent: str = ""


def _is_mcp_tool_call(node) -> bool:
    """`mcp.tool()` — the decorator, or the same call applied by hand."""
    return (isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "tool"
            and isinstance(node.func.value, ast.Name)
            and node.func.value.id == "mcp")


def _reaches_name(node) -> bool:
    """Whether this argument is the loop variable, through any wrapping calls.

    `_fn` and `_wrap_read(_fn)` both register `_fn` as a tool; only the second
    was invisible.
    """
    while isinstance(node, ast.Call) and node.args:
        node = node.args[0]
    return isinstance(node, ast.Name)


def exposed_tools() -> list[str]:
    """The tool names `server.py` actually defines. Parsed, not imported.

    Importing would need the MCP package and a configured graph; the point here
    is a check that runs anywhere, including in a test that must not touch a
    database.

    **Two registration forms, and missing the second one made the two generated
    surfaces disagree about the same server.** A regex for `@mcp.tool()` over a
    `def` saw fourteen; `guide.tools_page()` reads the live registry and
    correctly reported nineteen. The five it could not see -- the X-6e authoring
    tools -- are registered by a module-level loop, so no agent declared them and
    the docs said they existed.

    Module level is the discriminator, and it is the meaningful one: a
    registration that runs on import is a tool that always exists. The write
    tools are registered inside `_register_write_tools`, conditionally on
    `METIS_MCP_WRITE`, and are deliberately NOT collected here -- an agent at the
    default tier must not declare a tool that will not be there.

    **The loop body may wrap the function, and missing that lost the same five
    tools a third time.** `mcp.tool()(_fn)` became `mcp.tool()(_wrap_read(_fn))`
    when the authoring tools were given the `GraphNotConfigured` handling every
    other tool already had, and this parser silently dropped from 31 names to 26
    -- no error, just three agent tests failing about something else. So the
    first argument is now unwrapped through any call: what identifies a
    registration is the loop variable reaching `mcp.tool()`, not the shape of
    what surrounds it.
    """
    tree = ast.parse((Path(__file__).parent / "server.py").read_text())
    found: list[str] = []

    for node in tree.body:                      # module level only
        # `@mcp.tool()` on a `def`.
        if isinstance(node, ast.FunctionDef):
            if any(_is_mcp_tool_call(d) for d in node.decorator_list):
                found.append(node.name)
        # `for _fn in (mod.a, mod.b, ...): mcp.tool()(_fn)`
        elif isinstance(node, ast.For):
            applies = any(
                isinstance(stmt, ast.Expr)
                and isinstance(stmt.value, ast.Call)
                and _is_mcp_tool_call(stmt.value.func)
                and stmt.value.args
                and _reaches_name(stmt.value.args[0])
                for stmt in node.body)
            if applies and isinstance(node.iter, (ast.Tuple, ast.List)):
                found += [e.attr for e in node.iter.elts
                          if isinstance(e, ast.Attribute)]
    return found


def skill_files() -> list[Path]:
    """Every SKILL.md, top-level and specialist.

    **A specialist is a complete skill nested one directory deeper**, not a
    fragment of its parent: its own frontmatter, its own steps, its own refusals.
    The nesting records who maintains it. Discovery, the agent surface and the
    router all see a flat peer, which is why the `name:` is flat too.
    """
    return sorted(SKILLS.glob("*/SKILL.md")) + \
        sorted(SKILLS.glob("*/specialists/*/SKILL.md"))


def read_skills() -> list[Skill]:
    out: list[Skill] = []
    for path in skill_files():
        block = _FRONTMATTER.search(path.read_text())
        if not block:
            continue
        raw = block.group(1)
        fields = dict(
            (m.group(1), m.group(2).strip().strip('"'))
            for m in re.finditer(r"^([a-z-]+):\s*(.+)$", raw, re.M))
        if fields.get("name"):
            out.append(Skill(
                name=fields["name"],
                description=fields.get("description", ""),
                workflow=fields.get("workflow", ""),
                tools=_yaml_list(raw, "allowed-tools"),
                knowledge_from=_yaml_list(raw, "knowledge-from"),
                directory=path.parent,
                parent=(path.parent.parent.parent.name
                        if path.parent.parent.name == "specialists" else ""),
            ))
    return out


def _yaml_list(frontmatter: str, key: str) -> tuple[str, ...]:
    """The `- item` lines under `key:`, in order.

    A hand-rolled reader rather than PyYAML, for the reason the module docstring
    gives: this parses, it does not import, so it runs anywhere -- including in a
    test that must not load the server. The shape it accepts is the one the
    platform uses (`allowed-tools:` followed by `  - name` lines), and anything
    else is simply not matched rather than guessed at.
    """
    block = re.search(rf"^{re.escape(key)}:\s*\n((?:\s*-\s+.+\n?)+)",
                      frontmatter, re.M)
    if not block:
        return ()
    return tuple(m.group(1).strip()
                 for m in re.finditer(r"^\s*-\s+(.+)$", block.group(1), re.M))


def _first_sentence(text: str) -> str:
    return re.split(r"(?<=[.!?])\s+", text.strip(), maxsplit=1)[0]


# The negative section of a SKILL.md, whose numbered rules open with a bolded
# clause. Only that clause is lifted into the agent: the full section runs to
# forty lines, and an agent is a scope document, not a second copy of the skill.
_PROHIBITION = re.compile(r"^\d+\.\s+\*\*(.+?)\*\*", re.M)
_NEGATIVE_HEADINGS = ("## What this skill must not do", "## Non-negotiable rules",
                      "## Two rules this skill must not soften")


def skill_prohibitions(name: str) -> list[str]:
    """The bolded lead of each numbered rule in a skill's negative section.

    **This is the only place a skill's BODY reaches its agent.** Before it,
    everything an agent knew came from two frontmatter fields, so nine agents
    came out ninety-three lines identical. A skill's refusals are the part an
    agent most needs and the part it least had.

    Returns `[]` for a skill with no such section rather than raising -- one
    skill states its discipline as obligations ("report honestly") rather than
    prohibitions, and that is a legitimate shape, not a defect to fail on.
    """
    directory = next((s.directory for s in read_skills() if s.name == name), None)
    path = (directory or SKILLS / name) / "SKILL.md"
    if not path.exists():
        return []
    text = path.read_text()
    for heading in _NEGATIVE_HEADINGS:
        if heading not in text:
            continue
        section = text.split(heading, 1)[1]
        section = re.split(r"^## ", section, maxsplit=1, flags=re.M)[0]
        # Trailing punctuation is normalised because the sources disagree: some
        # rules close the bold before the period and some inside it, which reads
        # as carelessness once they are listed together.
        return [m.group(1).strip().rstrip(".").strip()
                for m in _PROHIBITION.finditer(section)]
    return []


def render_agent(skill: Skill, tools: list[str],
                 specialists: list[Skill] | None = None) -> str:
    """One agent per skill: its own tools, its own workflow, its own refusals.

    **What this used to be, because the failure is instructive.** Every agent got
    every tool and every workflow, and the only per-skill content was the name and
    the description -- each printed twice. Nine agents came out 97 lines with 93
    byte-identical, and half of each file was one tool list repeated. Nothing
    caught it: twelve tests asserted consistency and existence, none asserted that
    two agents differ.

    An agent is a **scope** document. It answers "which skill, with what
    permitted, refusing what" -- not "what is Metis", which is the router's job,
    and not "how is this done", which is the skill's.
    """
    from metis_mcp.workflow.stages import WORKFLOWS

    lines = [
        "---",
        f"name: {skill.name}",
        f"description: {_first_sentence(skill.description)}",
        "tools:",
    ]
    lines += [f"- {t}" for t in tools]
    lines += [
        "---",
        "",
        HEADER,
        "",
        f"# {skill.name}",
        "",
        skill.description,
        "",
        "## What this agent may reach",
        "",
        f"The {len(tools)} tools in this file's frontmatter, and no others \u2014 the",
        "working set of this skill rather than everything the server exposes. They",
        "are **read-only** (\u00a79.5, N-8, revised): landing, approving and publishing",
        "are separate tiers, and a gate's literal is never supplied here.",
        "",
        "The list is not repeated below. It used to be, and one list printed twice",
        "was half of every agent file.",
        "",
        "## Doing the work",
        "",
    ]

    workflow = WORKFLOWS.get(skill.workflow) if skill.workflow else None
    if workflow is not None:
        gates = [s for s in workflow.stages if s.is_gate]
        stages = " \u2192 ".join(s.name for s in workflow.ordered)
        lines += [
            f"This skill drives **`{skill.workflow}`** \u2014 {workflow.summary}",
            "",
            f"    {stages}",
            "",
            (f"It halts at **{gates[0].name}** for a human, and the literal that "
             f"passes that gate is theirs to give."
             if gates else "It has no gate."),
            "",
            "```",
            f"metis workflow run {skill.workflow} --scope <scope>",
            f"metis workflow status {skill.workflow}--<scope>",
            "```",
        ]
    else:
        lines += [
            "**This skill drives no workflow**, and that is not an omission: it",
            "wraps a single stage, tool, intake or gate. `metis workflow list`",
            f"shows the {len(WORKFLOWS)} that exist; the router chooses "
            "between them.",
        ]

    if specialists:
        lines += [
            "",
            "## Specialists this agent routes to",
            "",
            "They are **skills, not agents**: this agent selects one and follows",
            "it. Each states the prerequisites this parent has already enforced,",
            "so it does not re-derive them.",
            "",
        ]
        for child in specialists:
            lines.append(f"- **`{child.name}`** — "
                         f"{_first_sentence(child.description)}")
        lines += [
            "",
            "The routing rule is in the skill itself. When two seem to apply, the",
            "earlier step wins: the lifecycle runs in order and a later step",
            "consumes the earlier one's output.",
        ]

    prohibitions = skill_prohibitions(skill.name)
    if prohibitions:
        lines += [
            "",
            "## What this skill must not do",
            "",
            "Carried from the skill itself, because an agent that does not know its",
            "own refusals will be asked to make one and will not recognise it:",
            "",
        ]
        lines += [f"- {p}" for p in prohibitions]

    lines += [
        "",
        "## What this build does not have",
        "",
        "Named because an agent that advertises a capability it lacks fails in front",
        "of a user mid-task:",
        "",
        "- **call-graph impact analysis** \u2014 `Method`/`CALLS` are in the graph and "
        "nothing queries them (D-13). `impact` answers the file\u2192transition "
        "question and is not this",
        "- **traceability, as a chain that arrives** \u2014 `trace` walks D-4 and "
        "reports where it stops; it needs `AcceptanceCriterion-[:VALIDATES]->"
        "Transition` edges to reach a requirement, and there are zero",
        "- **explain-decision / explain-answer** \u2014 not implemented",
        # \u00a78.7 was REVISED: `execution_intake` lands TestExecution, TestCycle,
        # Defect, Metrics, Logs and Alert. This bullet said "no execution result
        # is ingested" long after they came back -- in all 26 generated agents,
        # because the sentence lives here. The C-11 half is still the load-bearing
        # reason and is kept; the second clause now says what actually stops a
        # verdict, which is that the two figures are deliberately never merged.
        "- **a release verdict** \u2014 `coverage_report` joins coverage, validation "
        "and reconciliation and states what it could not measure, but reaches no "
        "Go/No-Go: that would read a coverage figure as a claim about quality "
        "(C-11). Execution results ARE ingested (\u00a78.7, revised) and never write "
        "the coverage ledger, so *is this tested* and *did it pass* stay two "
        "figures and neither is a verdict",
        "- **submitting an episode** \u2014 a write, and this surface is read-only by "
        "construction",
        "",
    ]
    return "\n".join(lines) + "\n"


def generate() -> dict[str, str]:
    """`filename -> content` for every agent. Pure; writes nothing.

    **A skill that declares no `allowed-tools` gets the whole surface**, which is
    what every agent got before the field existed. Failing open is deliberate:
    scoping should be something a skill opts into as its author decides what it
    needs, not a migration that breaks nine agents on the day it lands.
    """
    available = exposed_tools()
    skills = read_skills()
    # **A specialist gets no agent of its own.** It is a skill its parent routes
    # to, and the parent's agent is the thing a client selects. Generating one
    # per specialist put four risk agents and three others in every client's
    # agent list, where they read as peers of the skill that owns them — the
    # nesting is ownership, and an agent surface flattened it back out.
    children: dict[str, list[Skill]] = {}
    for skill in skills:
        if skill.parent:
            children.setdefault(skill.parent, []).append(skill)

    agents = {}
    for skill in skills:
        if skill.parent:
            continue
        scoped = [t for t in skill.tools if t in available] or available
        agents[f"{skill.name}.agent.md"] = render_agent(
            skill, scoped, sorted(children.get(_directory_key(skill), []),
                                  key=lambda c: c.name))
    return agents


def _directory_key(skill: Skill) -> str:
    """The directory name a specialist records as its `parent`.

    A specialist stores its parent as the DIRECTORY name (`risk-manager`), while
    the skill's own `name` is the flat agent name (`metis-risk-manager`). Those
    differ for every skill whose folder drops the `metis-` prefix, so joining on
    `name` silently matches nothing and every parent renders with no specialists.
    """
    return skill.directory.name if skill.directory else skill.name


def stale_agents(target: Path) -> list[Path]:
    """Agent files in `target` that no live skill produces.

    A dead agent is worse than a missing one: it is confidently wrong, and it
    names tools a client will try to call.
    """
    expected = set(generate())
    return sorted(p for p in target.glob("*.agent.md")
                  if p.name not in expected and p.name != "metis.agent.md")


def write(target: Path | None = None, prune: bool = True) -> list[Path]:
    """Regenerate every agent surface. Removes dead files unless told not to.

    `metis.agent.md` is never touched here -- it is the router, generated from
    the workflow registry by `workflow.routing.render_router`, not from a skill.
    """
    targets = [Path(target)] if target else list(AGENT_TARGETS)
    written = []
    for directory in targets:
        directory.mkdir(parents=True, exist_ok=True)
        for filename, content in generate().items():
            path = directory / filename
            path.write_text(content)
            written.append(path)
        if prune:
            for dead in stale_agents(directory):
                dead.unlink()
    return written
