"""
Generate the client agent files from the skills and the real MCP surface.

**The agents were hand-maintained and drifted completely.** Every one of the five
under `.github/agents/` declared MCP tools — `metis_get_context`,
`metis_get_traceability`, `metis_check_coverage` and nine more — and **not one of
them exists**: twelve names referenced, seven exposed, zero overlap. Three of the
six skills they documented had been deleted. The generator that was supposed to
keep them honest went away with the v1 engine, so nothing regenerated and nothing
noticed.

This restores it, with the property that matters: an agent is a **view** over
things that are checked elsewhere, never a second place to state them.

  * the tool list comes from `server.py`'s actual `@mcp.tool()` functions
  * the skills come from `plugins/metis/skills/*/SKILL.md` frontmatter
  * the workflows come from `workflow.stages.WORKFLOWS`

So an agent cannot advertise a tool the server does not expose, or a skill that
does not exist, without this file being wrong -- and `test_agents.py` asserts the
checked-in files match what this produces, the same way `test_ontology.py`
asserts the schema matches `labels.py`.

**Tools are named, not invented.** Where a capability an old agent claimed has no
implementation -- impact analysis, traceability, explain-decision -- the agent
says so plainly rather than listing a tool that will fail on first call. An agent
that advertises what it cannot do is worse than one that admits a gap, because
the failure arrives in front of a user mid-task.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
SKILLS = REPO / "plugins" / "metis" / "skills"
AGENTS = REPO / ".github" / "agents"
# The Claude Code plugin's own agent surface, beside the router it already holds.
#
# **It was a third surface, generated by nothing and checked by nothing**, and it
# had rotted exactly as `test_agents.py`'s docstring predicts: four agents for
# skills that no longer exist, naming twelve MCP tools of which the server
# exposes none, and linking to a `metis-onboarding/SKILL.md` that is gone. Each
# file carried the "GENERATED ... do not hand-edit" banner while no generator
# had written to this directory in a long time.
PLUGIN_AGENTS = REPO / "plugins" / "metis" / "agents"
AGENT_TARGETS = (AGENTS, PLUGIN_AGENTS)

HEADER = ("<!-- GENERATED by metis_mcp/agent_generator.py from the skills' own "
          "frontmatter, the workflow registry, and server.py's real tool list. "
          "Do not hand-edit: regenerate, or the clients drift. -->")

_FRONTMATTER = re.compile(r"^---\n(.*?)\n---", re.S)
_TOOL = re.compile(r"@mcp\.tool\(\)\s*\ndef\s+([a-z_]+)\s*\(", re.M)


@dataclass(frozen=True)
class Skill:
    name: str
    description: str


def exposed_tools() -> list[str]:
    """The tool names `server.py` actually defines. Parsed, not imported.

    Importing would need the MCP package and a configured graph; the point here
    is a check that runs anywhere, including in a test that must not touch a
    database.
    """
    return _TOOL.findall((Path(__file__).parent / "server.py").read_text())


def read_skills() -> list[Skill]:
    out: list[Skill] = []
    for path in sorted(SKILLS.glob("*/SKILL.md")):
        block = _FRONTMATTER.search(path.read_text())
        if not block:
            continue
        fields = dict(
            (m.group(1), m.group(2).strip().strip('"'))
            for m in re.finditer(r"^([a-z-]+):\s*(.+)$", block.group(1), re.M))
        if fields.get("name"):
            out.append(Skill(fields["name"], fields.get("description", "")))
    return out


def _first_sentence(text: str) -> str:
    return re.split(r"(?<=[.!?])\s+", text.strip(), maxsplit=1)[0]


def render_agent(skill: Skill, tools: list[str]) -> str:
    """One agent per skill, declaring only tools that exist."""
    from metis_mcp.workflow.stages import WORKFLOWS

    lines = [
        "---",
        f"name: {skill.name}",
        f"description: {_first_sentence(skill.description)}",
        "tools:",
    ]
    lines += [f"- {t}" for t in tools]
    lines += [
        "---",
        "",
        HEADER,
        "",
        f"# {skill.name}",
        "",
        skill.description,
        "",
        "## The tools this agent has",
        "",
        "Every one is **read-only** (§9.5, N-8). No decision may be taken through",
        "this surface: a decision needs the evidence presentation N-3 specifies, and",
        "an agent session cannot provide it. Landing, approving and publishing go",
        "through the CLI, where the gates are.",
        "",
    ]
    lines += [f"- `{t}`" for t in tools]
    lines += [
        "",
        "## Doing the work",
        "",
        "The workflows below run through the CLI, not through a tool call:",
        "",
        "```",
        "metis workflow list",
        "metis workflow run <workflow> --scope <scope> ...",
        "metis workflow status <workflow>--<scope>",
        "```",
        "",
    ]
    for code, workflow in WORKFLOWS.items():
        gates = [s for s in workflow.stages if s.is_gate]
        gate_note = (f" Halts at **{gates[0].name}** for a human."
                     if gates else " No gates.")
        lines.append(f"- **`{code}`** — {workflow.summary}{gate_note}")
    lines += [
        "",
        "## What this build does not have",
        "",
        "Named because an agent that advertises a capability it lacks fails in front",
        "of a user mid-task:",
        "",
        "- **impact analysis** — `Method`/`CALLS` are in the graph, nothing queries them (D-13)",
        "- **traceability** — needs `AcceptanceCriterion-[:VALIDATES]->Transition`; there are zero",
        "- **explain-decision / explain-answer** — not implemented",
        "- **report generation** — no quality, release or test-design report exists",
        "- **submitting an episode** — a write, and this surface is read-only by construction",
        "",
    ]
    return "\n".join(lines) + "\n"


def generate() -> dict[str, str]:
    """`filename -> content` for every agent. Pure; writes nothing."""
    tools = exposed_tools()
    return {f"{skill.name}.agent.md": render_agent(skill, tools)
            for skill in read_skills()}


def stale_agents(target: Path) -> list[Path]:
    """Agent files in `target` that no live skill produces.

    A dead agent is worse than a missing one: it is confidently wrong, and it
    names tools a client will try to call.
    """
    expected = set(generate())
    return sorted(p for p in target.glob("*.agent.md")
                  if p.name not in expected and p.name != "metis.agent.md")


def write(target: Path | None = None, prune: bool = True) -> list[Path]:
    """Regenerate every agent surface. Removes dead files unless told not to.

    `metis.agent.md` is never touched here -- it is the router, generated from
    the workflow registry by `workflow.routing.render_router`, not from a skill.
    """
    targets = [Path(target)] if target else list(AGENT_TARGETS)
    written = []
    for directory in targets:
        directory.mkdir(parents=True, exist_ok=True)
        for filename, content in generate().items():
            path = directory / filename
            path.write_text(content)
            written.append(path)
        if prune:
            for dead in stale_agents(directory):
                dead.unlink()
    return written
