"""
The user guide, generated from what the engine actually is.

**Why generated rather than written.** Seven connector manifests lived in
`connectors/` for a long time and nothing ever opened them; four agent files in
`plugins/metis/agents/` named twelve tools that did not exist, each carrying a
"GENERATED — do not hand-edit" banner while no generator had written there in a
long time. Prose about a system drifts from the system silently, and the drift
is invisible precisely where it matters — a reader trusts documentation exactly
as much as its last correct sentence.

So every page here is produced from the source of truth it describes:
`ontology/labels.py`, `connectors/intakes.json`, `workflow/stages.py`, the
registered MCP tools, and the CLI parser. Each page says what it was generated
from. `test_guide.py` regenerates and diffs, so a stale guide is a failing build
rather than a surprise.

**Nothing here is authored.** A sentence that is not derivable from the tree
does not belong in this module — it belongs in `docs/academy/`, which is
authored on purpose and says so.

**One page is Python-version-specific, and this is the warning.** `cli_page`
captures argparse's `--help` output verbatim, and argparse's usage wrapping is
not stable across versions: 3.13 keeps the trailing `...` of a long subcommand
list on the previous line where 3.10-3.12 wrap it. The committed `cli.md`
therefore matches on **3.13 only**, and both `test_guide.py` and
`metis guide --check` compare bytes.

If `cli.md: differs` and you changed no CLI argument, check your interpreter
before you check your edit — CI pins 3.13 for exactly this reason. Regenerating
on an older Python and committing the result would move the failure to everyone
else rather than fixing it.
"""
from __future__ import annotations

import json
import pathlib
import subprocess
import sys

BANNER = (
    "<!-- GENERATED by `metis guide`. Do not hand-edit: the next run "
    "overwrites it, and `test_guide.py` fails on a diff. -->")

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent


class GuideRefused(Exception):
    """`metis guide` was run somewhere it cannot regenerate anything."""


def require_source_tree() -> pathlib.Path:
    """Refuse unless ROOT really is a Métis checkout.

    `ROOT` walks three parents up, which is the repository from a checkout and
    an arbitrary directory above `site-packages` from an installed wheel. Both
    inputs live there: `connectors/intakes.json`, which is outside the package
    and so is not shipped, and `docs/`, which is where the output goes.

    Without this the failure was `IntakesRefused: no intake declaration at
    <site-packages>/../connectors/intakes.json` -- a path that reads like a
    broken install rather than like "this command regenerates files that only
    exist in the repository". Shipping a copy of `intakes.json` inside the
    package would not have fixed it: the guide's *output* is `docs/`, which is
    equally absent, so a wheel would have written pages nobody can see.
    """
    if not (ROOT / "docs" / "metis-application-spec.md").is_file():
        raise GuideRefused(
            f"`metis guide` regenerates this repository's docs/guide/ from the "
            f"engine, so it only runs from a source checkout. Looked for the "
            f"tree at {ROOT} and found no docs/metis-application-spec.md. "
            f"Clone the repository and run it from there.")
    return ROOT


def _page(title: str, generated_from: str, body: list[str]) -> str:
    lines = [BANNER, "", f"# {title}", "",
             f"*Generated from `{generated_from}`.*", ""]
    lines += body
    return "\n".join(lines).rstrip() + "\n"


def ontology_page() -> str:
    from metis_mcp.ontology import labels

    body = [
        f"{len(labels.LABELS)} labels, {len(labels.ALLOWED_RELATIONSHIPS)} "
        f"relationships, {len(labels.STAGED_OUT)} staged out.",
        "",
        "The ontology is **closed**. Adding a label or a relationship is a "
        "reviewed change under D-2, not an edit — four places have to agree, "
        "and the Cypher schema is generated from `labels.py` so two of them "
        "cannot drift apart.",
        "",
        "## Labels", "",
    ]
    for label in sorted(labels.LABELS):
        # A specialisation is written INSTEAD of its parent, so a reader who
        # does not know this writes `MATCH (t:Transition)` and matches nothing.
        children = sorted(set(labels.specialisations_of(label)) - {label})
        rendered = ", ".join("`" + c + "`" for c in children)
        suffix = f" — written instead as {rendered}" if children else ""
        body.append(f"- `{label}`{suffix}")

    body += ["", "## Relationships", ""]
    for spec in sorted(labels.ALLOWED_RELATIONSHIPS,
                       key=lambda r: (r.from_label, r.rel_type, r.to_label)):
        body.append(f"- `{spec.from_label}` -[:{spec.rel_type}]-> "
                    f"`{spec.to_label}`")

    body += ["", "## Staged out", "",
             "Deliberately excluded. Each names the trigger that would bring "
             "it back — an absence with a reason is a decision; an absence "
             "without one is an oversight.", ""]
    for label, trigger in sorted(labels.STAGED_OUT.items()):
        body.append(f"- **`{label}`** — {trigger}")
    return _page("The ontology", "metis_mcp/ontology/labels.py", body)


def intakes_page() -> str:
    from metis_mcp import intakes

    body = [
        "Everything Métis reads. **No access mode runs anything** (X-7a): a "
        "database read for its structure is an intake source, and the same "
        "database reached to check a test's outcome is the System Under Test. "
        "Only the first is available, and that is structural — "
        "`executes_against_sut` is a schema `const` of `false`.",
        "",
        "| intake | status | access | command | reader |",
        "|---|---|---|---|---|",
    ]
    for intake in intakes.all_intakes():
        command = intake.get("command")
        rendered = f"`metis {' '.join(command)}`" if command else "—"
        body.append(f"| {intake['id']} | {intake['status']} | "
                    f"`{intake['access']}` | {rendered} | "
                    f"`{intake.get('reader', '—')}` |")

    body += ["", "### What in the source produces what", "",
             "`lands` names the labels; this names the thing in the source that "
             "produces each. Absent where the shape is not unambiguous — an "
             "invented shape is worse than none.", ""]
    for intake in intakes.all_intakes():
        mappings = intake.get("lands_from") or []
        if not mappings:
            continue
        body.append(f"**{intake['id']}**", )
        body.append("")
        body += [f"- {m['source_shape']} → `{m['label']}`" for m in mappings]
        body.append("")

    body += ["### When a fact is dated from", "",
             "Every `Episode` requires `t_recorded`. This says where it comes "
             "from, and how it misleads — an intake whose answer is "
             "\"extraction time\" says so rather than implying a real "
             "timestamp.", "",
             "| intake | anchored on | pitfall |", "|---|---|---|"]
    for intake in intakes.all_intakes():
        temporal = intake.get("temporal")
        if temporal:
            body.append(f"| {intake['id']} | {temporal['t_recorded_source']} | "
                        f"{temporal.get('known_pitfalls', '—')} |")

    body += ["", "### Reading a status", "",
             "| | |", "|---|---|",
             "| `working` | a reader exists and a test exercises it |",
             "| `partial` | a reader exists and something material is "
             "missing, named below |",
             "| `declared` | **no reader.** The capability does not exist |",
             "", "## Limits", ""]
    for intake in intakes.all_intakes():
        limits = intake.get("limits") or []
        if not limits:
            continue
        body.append(f"### {intake['id']}")
        body += [f"- {limit}" for limit in limits]
        body.append("")
    return _page("Intakes — what Métis reads", "connectors/intakes.json", body)


def workflows_page() -> str:
    from metis_mcp.workflow.stages import WORKFLOWS

    body = ["A stage marked **gate** stops for a person. Métis does not "
            "approve its own work: everything recovered lands at "
            "`Quarantine` (S-4) and generation reads only `Approved` (D-10).",
            ""]
    for code, workflow in sorted(WORKFLOWS.items()):
        body += [f"## `{code}`", "", workflow.summary, ""]
        if workflow.preconditions:
            body.append("**Preconditions:** "
                        + ", ".join(f"`{p}`" for p in workflow.preconditions))
            body.append("")
        body += ["| # | stage | gate | blocking |", "|---|---|---|---|"]
        for stage in workflow.ordered:
            body.append(f"| {stage.ordinal} | {stage.name} | "
                        f"{'**yes**' if stage.is_gate else ''} | "
                        f"{'yes' if stage.blocking else ''} |")
        body.append("")
    return _page("Workflows", "metis_mcp/workflow/stages.py", body)


def tools_page() -> str:
    import os

    from metis_mcp import server

    mode = os.environ.get("METIS_MCP_WRITE", "off")
    names = sorted(t.name for t in _tools(server.mcp))
    body = [
        f"`METIS_MCP_WRITE` is `{mode}` in the environment this was generated "
        "in. At `off` — the default — the write modules are never imported, so "
        "the read-only surface is not a policy but a fact about what exists "
        "(N-8, revised).",
        "",
        f"{len(names)} tools registered:", "",
    ]
    body += [f"- `{name}`" for name in names]
    body += ["", "Enabling writes adds landing and the gates, each costing an "
             "identity, the evidence fingerprint, and a literal confirmation "
             "word. The CLI remains the fullest surface."]
    return _page("The MCP surface", "metis_mcp/server.py", body)


def _tools(mcp):
    """The registered tools, whichever FastMCP internals hold them."""
    import asyncio

    try:
        return asyncio.run(mcp.list_tools())
    except Exception:                                     # pragma: no cover
        return []


def cli_page() -> str:
    out = subprocess.run(
        [sys.executable, "-m", "metis_mcp.mbt.cli", "--help"],
        capture_output=True, text=True, cwd=ROOT / "metis-server")
    body = ["```", out.stdout.strip(), "```"]
    return _page("The CLI", "metis_mcp/mbt/cli.py --help", body)


PAGES = {
    "README.md": None,          # built last, from the others
    "ontology.md": ontology_page,
    "intakes.md": intakes_page,
    "workflows.md": workflows_page,
    "mcp-tools.md": tools_page,
    "cli.md": cli_page,
}


def index_page() -> str:
    body = ["Generated from the engine, not written alongside it. Each page "
            "names its source.", ""]
    titles = {"ontology.md": "The ontology — 61 labels, closed under D-2",
              "intakes.md": "Intakes — what Métis reads, and what it refuses to",
              "workflows.md": "Workflows — the stages, and where each stops for a person",
              "mcp-tools.md": "The MCP surface — read-only by construction",
              "cli.md": "The CLI — the fullest surface"}
    for name, title in titles.items():
        body.append(f"- [{title}]({name})")
    body += ["", "For the reasoning rather than the reference, see "
             "`docs/academy/` — which is **authored**, and says so.",
             "", "The authoritative specification is "
             "`docs/metis-application-spec.md`. Where this guide and the spec "
             "disagree, the spec wins and this is a bug."]
    return _page("Métis — user guide", "metis_mcp/guide.py", body)


def generate() -> dict[str, str]:
    """`{filename: content}` for the whole guide."""
    require_source_tree()
    out = {"README.md": index_page()}
    for name, builder in PAGES.items():
        if builder is not None:
            out[name] = builder()
    return out


def write(directory) -> list[pathlib.Path]:
    target = pathlib.Path(directory)
    target.mkdir(parents=True, exist_ok=True)
    written = []
    for name, content in generate().items():
        path = target / name
        path.write_text(content)
        written.append(path)
    return sorted(written)
