"""
The user guide, generated from what the engine actually is.

**Why generated rather than written.** Seven connector manifests lived in
`connectors/` for a long time and nothing ever opened them; four agent files in
`plugins/metis/agents/` named twelve tools that did not exist, each carrying a
"GENERATED — do not hand-edit" banner while no generator had written there in a
long time. Prose about a system drifts from the system silently, and the drift
is invisible precisely where it matters — a reader trusts documentation exactly
as much as its last correct sentence.

So every page here is produced from the source of truth it describes:
`ontology/labels.py`, `connectors/intakes.json`, `workflow/stages.py`, the
registered MCP tools, and the CLI parser. Each page says what it was generated
from. `test_guide.py` regenerates and diffs, so a stale guide is a failing build
rather than a surprise.

**Nothing here is authored.** A sentence that is not derivable from the tree
does not belong in this module — it belongs in `docs/academy/`, which is
authored on purpose and says so.

**One page is Python-version-specific, and this is the warning.** `cli_page`
captures argparse's `--help` output verbatim, and argparse's usage wrapping is
not stable across versions: 3.13 keeps the trailing `...` of a long subcommand
list on the previous line where 3.10-3.12 wrap it. The committed `cli.md`
therefore matches on **3.13 only**, and both `test_guide.py` and
`metis guide --check` compare bytes.

If `cli.md: differs` and you changed no CLI argument, check your interpreter
before you check your edit — CI pins 3.13 for exactly this reason. Regenerating
on an older Python and committing the result would move the failure to everyone
else rather than fixing it.
"""
from __future__ import annotations

import json
import pathlib
import subprocess
import sys

BANNER = (
    "<!-- GENERATED by `metis guide`. Do not hand-edit: the next run "
    "overwrites it, and `test_guide.py` fails on a diff. -->")

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent


class GuideRefused(Exception):
    """`metis guide` was run somewhere it cannot regenerate anything."""


def require_source_tree() -> pathlib.Path:
    """Refuse unless ROOT really is a Métis checkout.

    `ROOT` walks three parents up, which is the repository from a checkout and
    an arbitrary directory above `site-packages` from an installed wheel. Both
    inputs live there: `connectors/intakes.json`, which is outside the package
    and so is not shipped, and `docs/`, which is where the output goes.

    Without this the failure was `IntakesRefused: no intake declaration at
    <site-packages>/../connectors/intakes.json` -- a path that reads like a
    broken install rather than like "this command regenerates files that only
    exist in the repository". Shipping a copy of `intakes.json` inside the
    package would not have fixed it: the guide's *output* is `docs/`, which is
    equally absent, so a wheel would have written pages nobody can see.
    """
    if not (ROOT / "docs" / "metis-application-spec.md").is_file():
        raise GuideRefused(
            f"`metis guide` regenerates this repository's docs/guide/ from the "
            f"engine, so it only runs from a source checkout. Looked for the "
            f"tree at {ROOT} and found no docs/metis-application-spec.md. "
            f"Clone the repository and run it from there.")
    return ROOT


def _page(title: str, generated_from: str, body: list[str]) -> str:
    lines = [BANNER, "", f"# {title}", "",
             f"*Generated from `{generated_from}`.*", ""]
    lines += body
    return "\n".join(lines).rstrip() + "\n"


def ontology_page() -> str:
    from metis_mcp.ontology import labels

    body = [
        f"{len(labels.LABELS)} labels, {len(labels.ALLOWED_RELATIONSHIPS)} "
        f"relationships, {len(labels.STAGED_OUT)} staged out.",
        "",
        "The ontology is **closed**. Adding a label or a relationship is a "
        "reviewed change under D-2, not an edit — four places have to agree, "
        "and the Cypher schema is generated from `labels.py` so two of them "
        "cannot drift apart.",
        "",
        "## Labels", "",
    ]
    for label in sorted(labels.LABELS):
        # A specialisation is written INSTEAD of its parent, so a reader who
        # does not know this writes `MATCH (t:Transition)` and matches nothing.
        children = sorted(set(labels.specialisations_of(label)) - {label})
        rendered = ", ".join("`" + c + "`" for c in children)
        suffix = f" — written instead as {rendered}" if children else ""
        body.append(f"- `{label}`{suffix}")

    body += ["", "## Relationships", ""]
    for spec in sorted(labels.ALLOWED_RELATIONSHIPS,
                       key=lambda r: (r.from_label, r.rel_type, r.to_label)):
        body.append(f"- `{spec.from_label}` -[:{spec.rel_type}]-> "
                    f"`{spec.to_label}`")

    body += ["", "## Staged out", "",
             "Deliberately excluded. Each names the trigger that would bring "
             "it back — an absence with a reason is a decision; an absence "
             "without one is an oversight.", ""]
    for label, trigger in sorted(labels.STAGED_OUT.items()):
        body.append(f"- **`{label}`** — {trigger}")
    return _page("The ontology", "metis_mcp/ontology/labels.py", body)


def intakes_page() -> str:
    from metis_mcp import intakes

    body = [
        "Everything Métis reads. **No access mode runs anything** (X-7a): a "
        "database read for its structure is an intake source, and the same "
        "database reached to check a test's outcome is the System Under Test. "
        "Only the first is available, and that is structural — "
        "`executes_against_sut` is a schema `const` of `false`.",
        "",
        "| intake | status | access | command | reader |",
        "|---|---|---|---|---|",
    ]
    for intake in intakes.all_intakes():
        command = intake.get("command")
        rendered = f"`metis {' '.join(command)}`" if command else "—"
        body.append(f"| {intake['id']} | {intake['status']} | "
                    f"`{intake['access']}` | {rendered} | "
                    f"`{intake.get('reader', '—')}` |")

    body += ["", "### What in the source produces what", "",
             "`lands` names the labels; this names the thing in the source that "
             "produces each. Absent where the shape is not unambiguous — an "
             "invented shape is worse than none.", ""]
    for intake in intakes.all_intakes():
        mappings = intake.get("lands_from") or []
        if not mappings:
            continue
        body.append(f"**{intake['id']}**", )
        body.append("")
        body += [f"- {m['source_shape']} → `{m['label']}`" for m in mappings]
        body.append("")

    body += ["### When a fact is dated from", "",
             "Every `Episode` requires `t_recorded`. This says where it comes "
             "from, and how it misleads — an intake whose answer is "
             "\"extraction time\" says so rather than implying a real "
             "timestamp.", "",
             "| intake | anchored on | pitfall |", "|---|---|---|"]
    for intake in intakes.all_intakes():
        temporal = intake.get("temporal")
        if temporal:
            body.append(f"| {intake['id']} | {temporal['t_recorded_source']} | "
                        f"{temporal.get('known_pitfalls', '—')} |")

    body += ["", "### Reading a status", "",
             "| | |", "|---|---|",
             "| `working` | a reader exists and a test exercises it |",
             "| `partial` | a reader exists and something material is "
             "missing, named below |",
             "| `declared` | **no reader.** The capability does not exist |",
             "", "## Limits", ""]
    for intake in intakes.all_intakes():
        limits = intake.get("limits") or []
        if not limits:
            continue
        body.append(f"### {intake['id']}")
        body += [f"- {limit}" for limit in limits]
        body.append("")
    return _page("Intakes — what Métis reads", "connectors/intakes.json", body)


def workflows_page() -> str:
    from metis_mcp.workflow.stages import WORKFLOWS

    body = ["A stage marked **gate** stops for a person. Métis does not "
            "approve its own work: everything recovered lands at "
            "`Quarantine` (S-4) and generation reads only `Approved` (D-10).",
            ""]
    for code, workflow in sorted(WORKFLOWS.items()):
        body += [f"## `{code}`", "", workflow.summary, ""]
        if workflow.preconditions:
            body.append("**Preconditions:** "
                        + ", ".join(f"`{p}`" for p in workflow.preconditions))
            body.append("")
        body += ["| # | stage | gate | blocking |", "|---|---|---|---|"]
        for stage in workflow.ordered:
            body.append(f"| {stage.ordinal} | {stage.name} | "
                        f"{'**yes**' if stage.is_gate else ''} | "
                        f"{'yes' if stage.blocking else ''} |")
        body.append("")
    return _page("Workflows", "metis_mcp/workflow/stages.py", body)


def tools_page() -> str:
    import os

    from metis_mcp import server

    mode = os.environ.get("METIS_MCP_WRITE", "off")
    names = sorted(t.name for t in _tools(server.mcp))
    body = [
        f"`METIS_MCP_WRITE` is `{mode}` in the environment this was generated "
        "in. At `off` — the default — the write modules are never imported, so "
        "the read-only surface is not a policy but a fact about what exists "
        "(N-8, revised).",
        "",
        f"{len(names)} tools registered:", "",
    ]
    body += [f"- `{name}`" for name in names]
    body += ["", "Enabling writes adds landing and the gates, each costing an "
             "identity, the evidence fingerprint, and a literal confirmation "
             "word. The CLI remains the fullest surface."]

    # **The surface is not only tools any more, and a page that said so would
    # be the dead list this file exists to replace.** Prompts and resources are
    # discovered from the skills and `docs/`, so they are reported by count and
    # by kind rather than enumerated -- naming ninety-seven documents here would
    # be a second copy of the tree.
    from metis_mcp import library

    described = library.describe()
    body += ["", "## Prompts and resources", ""]
    if not described.get("available"):
        body += [f"Not served by this deployment: {described['reason']}", ""]
    else:
        kinds = described.get("by_kind", {})
        body += [
            f"{described['prompts']} prompts and {described['resources']} "
            f"resources, discovered from `plugins/metis/skills/` and `docs/` "
            f"rather than declared here.",
            "",
            "A skill is a **prompt**: the procedure, its order, its gates, its "
            "refusals. Its steps, knowledge and references are **resources**, "
            "so progressive disclosure survives — `SKILL.md` is paid for when "
            "the prompt is invoked, and a step costs nothing until it is "
            "fetched.",
            "",
            "| Kind | Count |", "|---|---|",
        ]
        body += [f"| `{kind}` | {count} |"
                 for kind, count in sorted(kinds.items())]

        # **The prompts are named, and the resources are not.** Thirteen is an
        # inventory a person reads; ninety-seven is a copy of the tree. This
        # page is where `grep '@mcp.prompt'` sends a reader, because the
        # decorator deliberately does not exist — so the names have to be here
        # or they are nowhere.
        body += ["", "### The prompts", "",
                 "One per skill, discovered from `plugins/metis/skills/`. "
                 "There is no `@mcp.prompt` in `server.py` on purpose: "
                 "thirteen decorators would be a second copy of the skill "
                 "tree. This list is generated, so it cannot drift from it.",
                 ""]
        body += [f"- `{doc.name}`"
                 for doc in library.documents() if doc.kind == library.SKILL]
        body += ["", f"Resources are not listed: {described['resources']} of "
                 "them is the tree, not an inventory. Addressed as "
                 f"`{described['scheme']}` — `metis://skill/<name>`, "
                 "`metis://skill/<name>/steps/<step>`, `metis://guide/<page>`, "
                 "`metis://academy/<lesson>`, `metis://spec`."]

    return _page("The MCP surface", "metis_mcp/server.py", body)


def _tools(mcp):
    """The registered tools, whichever FastMCP internals hold them."""
    import asyncio

    try:
        return asyncio.run(mcp.list_tools())
    except Exception:                                     # pragma: no cover
        return []


def cli_page() -> str:
    out = subprocess.run(
        [sys.executable, "-m", "metis_mcp.mbt.cli", "--help"],
        capture_output=True, text=True, cwd=ROOT / "metis-server")
    body = ["```", out.stdout.strip(), "```"]
    return _page("The CLI", "metis_mcp/mbt/cli.py --help", body)


def surfaces_page() -> str:
    """Which surface holds what, and which client can reach it.

    **Written because the question kept being asked and the answer kept being
    assembled by hand.** Métis has four surfaces — MCP, skills, agents, the CLI
    — and two clients that can each reach a different subset. Every figure below
    is derived: the tools from the live registry, the skills and agents from the
    tree, the CLI from its own parser. A hand-written version of this page
    drifted three times in one session before it was generated.

    **This page counts a directory it is written into.** `library.documents()`
    globs `docs/guide/*.md`, and this page reports that count — so the run that
    first adds a guide page records the total from before it existed, and a
    second `metis guide` converges. `--check` catches the gap rather than
    hiding it, which is the behaviour worth keeping; the alternative was for
    the page to report a number derived from `PAGES` instead of from the tree,
    which would make it agree with itself and disagree with what is served.
    """
    import asyncio
    import re
    import subprocess
    import sys

    from metis_mcp import library, server
    from metis_mcp.agent_generator import AGENT_TARGETS, read_skills

    tools = sorted(t.name for t in _tools(server.mcp))
    prompts = sorted(p.name for p in asyncio.run(server.mcp.list_prompts()))
    described = library.describe()
    skills = read_skills()

    verbs = set()
    try:
        out = subprocess.run([sys.executable, "-m", "metis_mcp.mbt.cli", "--help"],
                             capture_output=True, text=True, timeout=60).stdout
        verbs = set(re.findall(r"^\s{4}([a-z][a-z-]+)", out, re.M))
    except Exception:                                     # pragma: no cover
        pass

    # A tool a person could otherwise reach from a shell. Named individually
    # rather than guessed, because a wrong pairing here would understate what is
    # lost by dropping the MCP surface.
    loose = {"coverage": "report", "flow_scaffold": "scaffold",
             "model_sources": "sources", "list_workflows": "workflow list",
             "run_status": "workflow status", "validate_model": "validate",
             "get_spec": "spec"}

    def analogue(name):
        if name in verbs:
            return name
        if name.replace("_", "-") in verbs:
            return name.replace("_", "-")
        return loose.get(name)

    only_mcp = [t for t in tools if not analogue(t)]
    shared = [(t, analogue(t)) for t in tools if analogue(t)]

    body = [
        "Four surfaces, two clients, and they do not overlap the way the "
        "directory tree suggests. Every count here is derived from the running "
        "system rather than restated.",
        "",
        "## Which client reaches what", "",
        "| Surface | Claude Code | Copilot |",
        "|---|---|---|",
        "| **MCP** — tools, prompts, resources | yes | yes |",
        "| The CLI, over a shell | yes | yes |",
        "| The plugin (`plugins/metis/`) — skills and agents | yes | via the marketplace |",
        "",
        "**Agents live in ONE place**, `plugins/metis/agents/`, and are "
        "distributed with the plugin. There was a byte-identical second copy "
        "under `.github/agents/` for Copilot to read directly; two copies of a "
        "generated artefact is two things to regenerate and one of them "
        "eventually is not, so the surface was collapsed to the plugin.",
        "",
        "A specialist has **no agent of its own** — its parent's agent routes to "
        "it as a skill, which is what keeps a client's agent list one entry per "
        "capability rather than one per file.",
        "",
        "## MCP", "",
        f"{len(tools)} tools, {described.get('prompts', 0)} prompts, "
        f"{described.get('resources', 0)} resources.",
        "",
        f"**{len(only_mcp)} of the {len(tools)} tools have no CLI path at "
        f"all.** This is the concrete cost of dropping the MCP surface: each "
        f"one would have to become a CLI verb or be deleted.",
        "",
    ]
    body += [f"- `{name}`" for name in only_mcp]
    body += ["", f"{len(shared)} have a CLI analogue:", ""]
    body += [f"- `{name}` ~ `metis {verb}`" for name, verb in shared]

    body += [
        "",
        "Prompts are the skills, read from the same files the plugin loads — "
        "one source, two transports, nothing to drift. Resources are the "
        "documents a step cites, so progressive disclosure survives the move.",
        "",
        "| Resource kind | Count |", "|---|---|",
    ]
    body += [f"| `{k}` | {v} |"
             for k, v in sorted(described.get("by_kind", {}).items())]

    body += [
        "", "## Skills", "",
        f"{len(skills)} under `plugins/metis/skills/`. Each declares its own "
        "`workflow:` and `allowed-tools:`, which is what the agents are "
        "generated from.",
        "",
    ]
    body += [f"- `{s.name}`" + (f" — drives `{s.workflow}`" if s.workflow else "")
             for s in skills]

    body += ["", "## Agents", ""]
    body += [f"- `{target.relative_to(library.repo())}` — "
             f"{len(list(target.glob('*.agent.md')))} files"
             for target in AGENT_TARGETS]
    scopes = {s.name: len(s.tools) for s in skills}
    body += [
        "",
        f"Generated from the skills' frontmatter. They hold scope and nothing "
        f"else: {len(set(frozenset(s.tools) for s in skills))} distinct tool "
        f"sets, {min(scopes.values())}–{max(scopes.values())} tools each out "
        f"of {len(tools)}. **MCP has no primitive for this** — neither a "
        "prompt nor a resource has a field expressing tool scope — which is "
        "why agents stay on the filesystem in both client formats.",
        "",
        "## The CLI", "",
        f"{len(verbs)} top-level verbs, and the fullest surface. **The gates "
        "live here and only here**: `metis publish` is G2, `metis review "
        "export` / `apply` is the diffable decision file (N-7). "
        "`resume_workflow` on the MCP surface deliberately accepts no "
        "confirmation, so an agent cannot supply G2's literal itself.",
    ]
    return _page("The surfaces, and who can reach them",
                 "the live MCP registry, the skill tree and the CLI parser",
                 body)


PAGES = {
    "README.md": None,          # built last, from the others
    "ontology.md": ontology_page,
    "intakes.md": intakes_page,
    "workflows.md": workflows_page,
    "mcp-tools.md": tools_page,
    "cli.md": cli_page,
    "surfaces.md": surfaces_page,
}


def index_page() -> str:
    body = ["Generated from the engine, not written alongside it. Each page "
            "names its source.", ""]
    titles = {"ontology.md": "The ontology — 61 labels, closed under D-2",
              "intakes.md": "Intakes — what Métis reads, and what it refuses to",
              "workflows.md": "Workflows — the stages, and where each stops for a person",
              "mcp-tools.md": "The MCP surface — read-only by construction",
              "cli.md": "The CLI — the fullest surface"}
    for name, title in titles.items():
        body.append(f"- [{title}]({name})")
    body += ["", "For the reasoning rather than the reference, see "
             "`docs/academy/` — which is **authored**, and says so.",
             "", "The authoritative specification is "
             "`docs/metis-application-spec.md`. Where this guide and the spec "
             "disagree, the spec wins and this is a bug."]
    return _page("Métis — user guide", "metis_mcp/guide.py", body)


def generate() -> dict[str, str]:
    """`{filename: content}` for the whole guide."""
    require_source_tree()
    out = {"README.md": index_page()}
    for name, builder in PAGES.items():
        if builder is not None:
            out[name] = builder()
    return out


def write(directory) -> list[pathlib.Path]:
    target = pathlib.Path(directory)
    target.mkdir(parents=True, exist_ok=True)
    written = []
    for name, content in generate().items():
        path = target / name
        path.write_text(content)
        written.append(path)
    return sorted(written)
