"""
Generate each skill's `knowledge/` from the module docstrings it names.

**The problem this solves, measured.** `metis_mcp/` carries 11,768 lines of
docstring and comment — 37% of its non-blank Python, and more than the
application spec, the whole skill tree, the academy, the guide, CLAUDE.md and the
README combined. It is the real design knowledge: why a rule exists, what broke
before it did, which alternative was rejected. And it is addressed to a
maintainer reading source. An agent doing model-build loads about 175 lines of
skill and never sees any of it.

**Why generation rather than a rewrite.** Moving the prose out of the code would
put it where an agent can read it and take it away from where the decision is
implemented — which is exactly why it works. So the docstring stays the source of
truth and this emits a copy beside the skill that needs it, the same arrangement
`guide.py` has with `docs/guide/`. `metis knowledge --check` fails on a diff, so
the copy cannot drift.

**Module docstrings only, and that is a size decision.** They run 20–50 lines and
are already written as argued prose. Function docstrings are 7,579 lines and
would bury the skill they were meant to serve — the point of a `knowledge/` file
is that a step can afford to cite it.

**Parsed, never imported.** `ast.get_docstring` over the file, for the reason
`agent_generator.exposed_tools` gives: a generator that imported the package
would need a configured graph and would drag write paths into a process that
only wanted to read prose.

Every skill gets an `index.md` even when it names no modules. Emptiness is a
decision and it is recorded rather than left as an absent directory somebody has
to interpret.
"""
from __future__ import annotations

import ast
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
SKILLS = REPO / "plugins" / "metis" / "skills"
PACKAGE = Path(__file__).resolve().parent

BANNER = ("<!-- GENERATED by `metis knowledge` from the module docstring named "
          "in this skill's frontmatter. Do not hand-edit: the source of truth is "
          "the docstring, and `metis knowledge --check` fails on a diff. -->")


def module_path(dotted: str) -> Path:
    """`publishing.publish` -> the file, without importing it."""
    return PACKAGE.joinpath(*dotted.split(".")).with_suffix(".py")


def module_docstring(dotted: str) -> str | None:
    path = module_path(dotted)
    if not path.exists():
        return None
    try:
        return ast.get_docstring(ast.parse(path.read_text()), clean=True)
    except SyntaxError:
        return None


def _slug(dotted: str) -> str:
    return dotted.replace(".", "-")


def render_fragment(dotted: str, docstring: str) -> str:
    """One knowledge file: the docstring, and where it came from."""
    title = dotted.split(".")[-1].replace("_", " ")
    return "\n".join([
        BANNER,
        "",
        f"# {title}",
        "",
        f"*The design argument behind `metis_mcp/{dotted.replace('.', '/')}.py`, "
        f"which is where it is maintained.*",
        "",
        docstring.strip(),
        "",
    ])


def render_index(skill: str, modules: list[str], inherited: list[str] | None = None,
                 parent: str = "") -> str:
    """What is here, what is inherited, and — when nothing is — why not."""
    inherited = list(inherited or [])
    lines = [BANNER, "", f"# Knowledge index — {skill}", ""]

    if inherited:
        # Named rather than silently absent. A reader who finds no
        # `ontology-labels.md` here would otherwise conclude this skill does not
        # depend on it, when the truth is that the parent already carries it.
        lines += [
            f"**Inherited from `{parent}`** — already in context when this",
            "specialist runs, so it is not copied here:",
            "",
        ]
        lines += [f"- `{_slug(d)}` — from `metis_mcp/{d.replace('.', '/')}.py`"
                  for d in inherited]
        lines.append("")

    if not modules and inherited:
        lines += [
            "Nothing further is extracted for this specialist: everything it",
            "declares is its parent's, which is what makes it a specialist rather",
            "than a separate skill.",
        ]
        return "\n".join(lines) + "\n"

    if not modules:
        lines += [
            "**Nothing is extracted for this skill, and that is a decision.**",
            "",
            "Its frontmatter names no `knowledge-from` module. The discipline this",
            "skill needs is either always-enforced — in which case it belongs in",
            "`../SKILL.md`, which is loaded every time — or it is shared, in which",
            "case it is in `../shared/knowledge/` and cited from a step.",
            "",
            "A fragment earns its place here when a step needs the reasoning and",
            "paying for it on every invocation would be waste.",
        ]
        return "\n".join(lines) + "\n"

    lines += [
        "Each fragment is generated from the module docstring that is its source",
        "of truth. Read one when a step cites it, not before — that is what makes",
        "a fragment cheaper than putting the same prose in `../SKILL.md`.",
        "",
        "| Fragment | Generated from |",
        "|---|---|",
    ]
    for dotted in modules:
        lines.append(f"| [`{_slug(dotted)}.md`]({_slug(dotted)}.md) "
                     f"| `metis_mcp/{dotted.replace('.', '/')}.py` |")
    return "\n".join(lines) + "\n"


def generate() -> dict[Path, str]:
    """`path -> content` for every knowledge file. Pure; writes nothing."""
    from metis_mcp.agent_generator import read_skills

    skills = read_skills()
    # What each PARENT already loads, keyed by its directory name — which is
    # what a specialist records in `parent`, not the parent's flat skill name.
    by_directory = {s.directory.name: s for s in skills if s.directory}

    out: dict[Path, str] = {}
    for skill in skills:
        directory = (skill.directory or SKILLS / skill.name) / "knowledge"
        named = [m for m in skill.knowledge_from if module_docstring(m)]

        # **A specialist does not re-emit a fragment its parent already has.**
        # A specialist opens by stating the prerequisites the parent enforced, so
        # the parent's knowledge is already in context when the specialist runs;
        # generating a second copy produced three byte-identical file pairs and
        # paid for the same docstring twice. The skill may still DECLARE the
        # module — that is how it says what it depends on — it just does not get
        # its own copy of the file.
        inherited: list[str] = []
        if skill.parent:
            owner = by_directory.get(skill.parent)
            if owner:
                inherited = [m for m in named if m in owner.knowledge_from]
                named = [m for m in named if m not in inherited]

        for dotted in named:
            out[directory / f"{_slug(dotted)}.md"] = render_fragment(
                dotted, module_docstring(dotted) or "")
        out[directory / "index.md"] = render_index(
            skill.name, named, inherited=inherited,
            parent=skill.parent if inherited else "")
    return out


def write() -> list[Path]:
    written = []
    for path, content in sorted(generate().items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text() != content:
            path.write_text(content)
        written.append(path)
    return written


def stale() -> list[Path]:
    """Knowledge files no skill produces any more.

    A fragment left behind after its `knowledge-from` entry is removed is worse
    than a missing one: it is confidently out of date and nothing points at it.
    """
    expected = set(generate())
    # `shared/knowledge/` is AUTHORED, not generated -- the anti-hallucination
    # protocol and the ported condition-coverage discipline are prose somebody
    # wrote and nothing derives. Reporting them as stale would invite deleting
    # them, which is the opposite of what this check is for. The distinction is
    # the whole reason `shared/` exists beside the per-skill directories.
    # **Both depths.** This globbed `*/knowledge/*.md` only, so a specialist's
    # knowledge directory — `*/specialists/*/knowledge/` — was never scanned and
    # a stale fragment there could never be reported. Nothing noticed because
    # nothing had gone stale at that depth yet.
    found = {p for p in (*SKILLS.glob("*/knowledge/*.md"),
                         *SKILLS.glob("*/specialists/*/knowledge/*.md"))
             if p.parent.parent.name != "shared"}
    return sorted(found - expected)


def check() -> list[str]:
    """What differs between the tree and what this would generate."""
    problems = []
    for path, content in sorted(generate().items()):
        if not path.exists():
            problems.append(f"{path.relative_to(REPO)}: missing")
        elif path.read_text() != content:
            problems.append(f"{path.relative_to(REPO)}: differs from the docstring")
    for path in stale():
        problems.append(f"{path.relative_to(REPO)}: no skill produces this")
    return problems
