"""
Stages 4-5 of the Behavior Model test pipeline
(docs/metis-behavior-model-test-pipeline.md): deterministic skeleton
generation for a Transition's gapped layers (Stage 3's output, real
`pyramid_gap_check.py`), optional real LLM body-fill, and Stage 5
commit-back.

Per the pipeline diagram (§1), Stage 3 only ever branches to two
generation targets -- "Functional test skeleton" and, if
Performance:SLA-critical, "Performance test skeleton" -- unit/integration
gaps are surfaced as findings (feeding the DQ-008a/b amendment), not
generation targets; ordinary developer practice is expected to close
those, not this pipeline. So `propose_test_skeletons` only ever generates
for `functional`/`performance`, even if `pyramid_gap_check` reports a
`unit`/`integration` gap too.

CONST-050/REQ-METIS-BM-05: once a completeness violation (behavior_model.py's
check_completeness -- an undefined Trigger-in-State) is resolved by a human
adding the missing real Transition, that Transition's generated functional
test must be traceable back to the gap it closes. Detected here
deterministically: if this Transition is the *only* one firing on its
(from_state, trigger) pair, its existence is what keeps that pair off the
completeness-gap list -- i.e. it's the resolution.

Stage 4's body-fill ("§9.2, RPI-gated") is genuine LLM judgment, per
llm_client.py's cost-awareness convention -- never called automatically;
a caller must explicitly request it via body_fill_skeleton.

Stage 5 commit-back (CONST-045/REQ-METIS-CONN-06, REQ-METIS-BM-03): a
generated test MUST carry a valid, project-configured traceability
annotation before commit-back -- fabricating one when no
`project_test_id_conventions` entry is confirmed for the target repo would
violate the exact no-fabrication discipline this whole platform is built
on (connectors/metis-connector-test-suite.json's own REQ-METIS-CONN-06
comment: "halts ... does NOT fall back to guessing a pattern"). No such
entry exists for this project (checked: only the schema's REPLACE
placeholder is present) -- so real commit-back against this codebase
correctly halts rather than inventing a convention. Separately, and
independently: this directory is not a git repository (confirmed via
environment info), so even a configured project cannot get a real PR here
-- disclosed explicitly, not faked with a placeholder PR URL.
"""
import json
import os
from dataclasses import dataclass, field

from metis_mcp.llm_client import call_llm, LLMCallError
from metis_mcp.pyramid_gap_check import check_pyramid_gaps

GENERATION_TARGET_LAYERS = ("api_functional", "web_functional", "performance")

BODY_FILL_SYSTEM_PROMPT = (
    "You are filling in the body of a generated pytest test skeleton for a "
    "state-machine Transition in the Metis platform. You are given the "
    "skeleton's TODO markers and the real Transition data (from_state, "
    "to_state, trigger, guard). Write ONLY real, runnable pytest assertions "
    "that check the transition's guard/action semantics. Do not invent "
    "business logic not implied by the given data. Return ONLY the completed "
    "Python function body, no markdown fences, no commentary."
)


@dataclass
class TransitionDetail:
    transition_id: str
    from_state: str
    to_state: str
    trigger: str
    guard_expression: str


def _fetch_transition_detail(session, transition_id: str) -> TransitionDetail | None:
    rec = session.run(
        """
        MATCH (from:State)-[:WHEN]->(t:Transition {id: $id})-[:THEN]->(to:State)
        RETURN from.id AS from_state, to.id AS to_state,
               t.trigger AS trigger, t.guard_expression AS guard_expression
        """,
        id=transition_id,
    ).single()
    if rec is None or rec["trigger"] is None or rec["guard_expression"] is None:
        return None
    return TransitionDetail(
        transition_id=transition_id, from_state=rec["from_state"], to_state=rec["to_state"],
        trigger=rec["trigger"], guard_expression=rec["guard_expression"],
    )


def _resolves_completeness_gap(session, detail: TransitionDetail) -> bool:
    """True iff this Transition is the only one firing on its
    (from_state, trigger) pair -- i.e. its existence is the entire reason
    that pair isn't currently reported by check_completeness()."""
    rec = session.run(
        """
        MATCH (s:State {id: $from_state})-[:WHEN]->(t:Transition)
        WHERE t.trigger = $trigger
        RETURN count(t) AS c
        """,
        from_state=detail.from_state, trigger=detail.trigger,
    ).single()
    return bool(rec) and rec["c"] == 1


def _skeleton_code(detail: TransitionDetail, test_type: str, fn_name: str) -> str:
    return f'''def {fn_name}():
    """Generated by Metis Stage 4 (metis_propose_test_skeleton) from
    Transition '{detail.transition_id}' -- requires_human_review, never
    auto-committed. test_type={test_type}."""
    # Arrange: system is in state '{detail.from_state}'
    # TODO(body-fill): construct real fixture putting the system under test
    #                   into state '{detail.from_state}'.

    # Act: fire trigger '{detail.trigger}'
    # TODO(body-fill): invoke the real implementing behavior for trigger
    #                   '{detail.trigger}' while guard "{detail.guard_expression}" holds.

    # Assert: system transitions to state '{detail.to_state}'
    # TODO(body-fill): assert the system is now in state '{detail.to_state}',
    #                   and remains in '{detail.from_state}' if the guard does not hold.
    raise NotImplementedError("skeleton only -- body-fill required before this test is real")
'''


def _generate_one(session, detail: TransitionDetail, test_type: str, closes_gap: bool) -> dict:
    fn_name = f"test_{detail.transition_id.replace(':', '_').replace('-', '_')}_{test_type}"
    return {
        "test_type": test_type,
        "fixtures": [f"state_fixture__{detail.from_state}", f"trigger_fixture__{detail.trigger}"],
        "assertions_targeted": [
            f"transitions from '{detail.from_state}' to '{detail.to_state}' when "
            f"'{detail.trigger}' fires and guard \"{detail.guard_expression}\" holds",
            f"remains in '{detail.from_state}' if guard \"{detail.guard_expression}\" does not hold",
        ],
        "skeleton_code": _skeleton_code(detail, test_type, fn_name),
        "function_name": fn_name,
        "closes_completeness_gap": closes_gap,
    }


def propose_test_skeletons(session, transition_id: str) -> dict:
    """The real implementation behind metis_propose_test_skeleton when
    graph.backend == 'neo4j'. Returns the mcp-contracts required shape
    (transition_id, skeleton, requires_human_review) plus real additional
    fields (pyramid_gap_check, skeletons) -- the contract doesn't forbid
    extra properties, and collapsing multiple real gapped-layer skeletons
    into a single required `skeleton` field would silently drop one."""
    gap_result = check_pyramid_gaps(session, transition_id)
    if not gap_result.determinable:
        return {
            "transition_id": transition_id,
            "applicable": False,
            "reason": gap_result.reason,
            "skeleton": None,
            "requires_human_review": True,
        }

    detail = _fetch_transition_detail(session, transition_id)
    if detail is None:
        return {
            "transition_id": transition_id,
            "applicable": False,
            "reason": f"Transition '{transition_id}' has implementing_method_id but its "
                      f"State/trigger/guard_expression data is incomplete -- cannot template a skeleton.",
            "skeleton": None,
            "requires_human_review": True,
        }

    targets = [layer for layer in gap_result.gaps if layer in GENERATION_TARGET_LAYERS]
    closes_gap = _resolves_completeness_gap(session, detail)
    skeletons = [_generate_one(session, detail, layer, closes_gap) for layer in targets]

    return {
        "transition_id": transition_id,
        "applicable": True,
        "skeleton": skeletons[0] if skeletons else None,
        "skeletons": skeletons,
        "requires_human_review": True,
        "pyramid_gap_check": {
            "coverage": gap_result.coverage,
            "covering_test_ids": gap_result.covering_test_ids,
            "gaps": gap_result.gaps,
            "generation_targets": targets,
            "reason": gap_result.reason,
        },
        "note": None if skeletons else (
            "No functional/performance gap for this Transition -- REQ-METIS-PG-01: generation "
            "never fires for an already-covered layer. Unit/integration coverage is a separate "
            "finding (DQ-008a/b), not a generation target for this pipeline."
        ),
    }


def body_fill_skeleton(skeleton: dict, model: str = "sonnet") -> dict:
    """Stage 4's genuinely-judgment body-fill (§9.2). Deliberate, explicit
    call only -- real, costed model call via llm_client.py, same
    cost-awareness convention as llm_judge.py/microrequirement.py. Returns
    the skeleton dict with `skeleton_code` replaced by the filled body and
    a real `body_fill_cost_usd` recorded, or `body_fill_error` set if the
    call fails (never silently falls back to the unfilled skeleton without
    saying so)."""
    prompt = (
        f"Transition skeleton (test_type={skeleton['test_type']}):\n\n"
        f"{skeleton['skeleton_code']}\n\n"
        f"assertions_targeted: {json.dumps(skeleton['assertions_targeted'])}\n"
        f"fixtures: {json.dumps(skeleton['fixtures'])}\n\n"
        "Replace the TODO(body-fill) sections with real pytest code implementing "
        "the arrange/act/assert steps described. Keep the function signature and "
        "docstring. Return the complete function."
    )
    try:
        response = call_llm(prompt, model=model, system_prompt=BODY_FILL_SYSTEM_PROMPT)
    except LLMCallError as e:
        return {**skeleton, "body_filled": False, "body_fill_error": str(e)}

    return {
        **skeleton,
        "skeleton_code": response.text,
        "body_filled": True,
        "body_fill_model": response.model,
        "body_fill_cost_usd": response.cost_usd,
        "body_fill_input_tokens": response.input_tokens,
        "body_fill_output_tokens": response.output_tokens,
    }


def commit_generated_test(session, transition_id: str, skeleton: dict, repo: str,
                           source_episode_id: str,
                           project_test_id_conventions: dict | None = None,
                           output_dir: str = "generated_tests") -> dict:
    """Stage 5 (§4). CONST-045: refuses to commit without a real, confirmed
    per-project traceability convention (REQ-METIS-CONN-06) -- no
    fabricated `@TestId`-style annotation is invented when a project's
    convention isn't confirmed (connectors/metis-connector-test-suite.json's
    own REQ-METIS-CONN-06 halt rule, applied identically here).

    `project_test_id_conventions` mirrors the connector manifest's
    per-project entry shape: {repo: {"pattern_type": ..., "pattern": ...}}.
    None/missing entry for `repo` -> halt, do not proceed on a guess.
    """
    entry = (project_test_id_conventions or {}).get(repo)
    if not entry:
        return {
            "transition_id": transition_id, "committed": False, "pr_created": False,
            "reason": f"No confirmed project_test_id_conventions entry for repo '{repo}' "
                      f"(REQ-METIS-CONN-06) -- CONST-045 requires a valid traceability "
                      f"annotation before commit-back; refusing to fabricate one. Halt here, "
                      f"same discipline as test-suite-ingest's own per-project resolution.",
        }

    pattern_type = entry.get("pattern_type")
    trace_id = f"TR-{transition_id.split(':')[-1]}"
    if pattern_type == "annotation":
        annotation = f'@TestId("{trace_id}")\n'
    elif pattern_type == "comment_tag":
        annotation = f"# TC-ID: {trace_id}\n"
    else:
        return {
            "transition_id": transition_id, "committed": False, "pr_created": False,
            "reason": f"repo '{repo}' has an unrecognized pattern_type '{pattern_type}' -- "
                      f"refusing to guess an annotation format.",
        }

    fn_name = skeleton.get("function_name", f"test_{transition_id.replace(':', '_')}")
    file_name = f"{fn_name}.py"
    os.makedirs(output_dir, exist_ok=True)
    file_path = os.path.join(output_dir, file_name)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(annotation)
        f.write(skeleton["skeleton_code"])

    generated_test_id = f"{repo}:{output_dir}/{file_name}:{fn_name}"

    def _write(tx):
        tx.run(
            """
            MERGE (gt:GeneratedTest {id: $id})
            SET gt.source_episode_id = $episode, gt.transition_id = $transition_id,
                gt.test_type = $test_type, gt.trace_id = $trace_id,
                gt.file_path = $file_path, gt.committed_to_repo = false,
                gt.lifecycle_state = 'PendingCommit',
                gt.closes_completeness_gap = $closes_gap
            WITH gt
            MATCH (t:Transition {id: $transition_id})
            MERGE (gt)-[:GENERATED_FROM]->(t)
            """,
            id=generated_test_id, episode=source_episode_id, transition_id=transition_id,
            test_type=skeleton["test_type"], trace_id=trace_id, file_path=file_path,
            closes_gap=skeleton.get("closes_completeness_gap", False),
        )
    session.execute_write(_write)

    return {
        "transition_id": transition_id, "generated_test_id": generated_test_id,
        "committed": True, "file_path": file_path, "trace_id": trace_id,
        "pr_created": False,
        "reason": "File written and :GeneratedTest provenance recorded (REQ-METIS-BM-03, "
                  "permanent, never erased) -- but this directory is not a git repository "
                  "(confirmed via environment info), so no real commit/PR can be created here. "
                  "In a real deployment this step opens a PR via the merge-request-creator "
                  "pattern (§4.3); that part is genuinely blocked in this environment, not faked.",
    }
