// ==========================================================
// Métis Graph Schema -- Part 1: Per-entity baseline constraints
// AUTO-GENERATED by generate_cypher.py -- do not hand-edit this
// file directly; regenerate it if the entity list changes.
// Neo4j 2026.x syntax (CREATE CONSTRAINT IF NOT EXISTS).
// ==========================================================

// ---- Business layer ----
CREATE CONSTRAINT goal_id_unique IF NOT EXISTS FOR (n:Goal) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT goal_source_episode_required IF NOT EXISTS FOR (n:Goal) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX goal_lifecycle_state IF NOT EXISTS FOR (n:Goal) ON (n.lifecycle_state);
CREATE INDEX goal_t_valid IF NOT EXISTS FOR (n:Goal) ON (n.t_valid);
CREATE INDEX goal_t_invalid IF NOT EXISTS FOR (n:Goal) ON (n.t_invalid);
CREATE CONSTRAINT capability_id_unique IF NOT EXISTS FOR (n:Capability) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT capability_source_episode_required IF NOT EXISTS FOR (n:Capability) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX capability_lifecycle_state IF NOT EXISTS FOR (n:Capability) ON (n.lifecycle_state);
CREATE INDEX capability_t_valid IF NOT EXISTS FOR (n:Capability) ON (n.t_valid);
CREATE INDEX capability_t_invalid IF NOT EXISTS FOR (n:Capability) ON (n.t_invalid);
CREATE CONSTRAINT epic_id_unique IF NOT EXISTS FOR (n:Epic) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT epic_source_episode_required IF NOT EXISTS FOR (n:Epic) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX epic_lifecycle_state IF NOT EXISTS FOR (n:Epic) ON (n.lifecycle_state);
CREATE INDEX epic_t_valid IF NOT EXISTS FOR (n:Epic) ON (n.t_valid);
CREATE INDEX epic_t_invalid IF NOT EXISTS FOR (n:Epic) ON (n.t_invalid);
CREATE CONSTRAINT feature_id_unique IF NOT EXISTS FOR (n:Feature) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT feature_source_episode_required IF NOT EXISTS FOR (n:Feature) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX feature_lifecycle_state IF NOT EXISTS FOR (n:Feature) ON (n.lifecycle_state);
CREATE INDEX feature_t_valid IF NOT EXISTS FOR (n:Feature) ON (n.t_valid);
CREATE INDEX feature_t_invalid IF NOT EXISTS FOR (n:Feature) ON (n.t_invalid);

// ---- Jira evidence layer (Session 14) -- JiraItem is the explicit
// evidence-anchor node for a real Jira issue; jira_key is site-qualified so
// it stays globally unique across Atlassian sites, never a bare project key.
CREATE CONSTRAINT jiraitem_id_unique IF NOT EXISTS FOR (n:JiraItem) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT jiraitem_source_episode_required IF NOT EXISTS FOR (n:JiraItem) REQUIRE n.source_episode_id IS NOT NULL;
CREATE CONSTRAINT jiraitem_jira_key_required IF NOT EXISTS FOR (n:JiraItem) REQUIRE n.jira_key IS NOT NULL;
CREATE CONSTRAINT jiraitem_issue_type_required IF NOT EXISTS FOR (n:JiraItem) REQUIRE n.issue_type IS NOT NULL;
CREATE INDEX jiraitem_lifecycle_state IF NOT EXISTS FOR (n:JiraItem) ON (n.lifecycle_state);
CREATE INDEX jiraitem_t_valid IF NOT EXISTS FOR (n:JiraItem) ON (n.t_valid);
CREATE INDEX jiraitem_t_invalid IF NOT EXISTS FOR (n:JiraItem) ON (n.t_invalid);
CREATE INDEX jiraitem_jira_key_lookup IF NOT EXISTS FOR (n:JiraItem) ON (n.jira_key);

// ---- Requirement layer ----
CREATE CONSTRAINT requirement_id_unique IF NOT EXISTS FOR (n:Requirement) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT requirement_source_episode_required IF NOT EXISTS FOR (n:Requirement) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX requirement_lifecycle_state IF NOT EXISTS FOR (n:Requirement) ON (n.lifecycle_state);
CREATE INDEX requirement_t_valid IF NOT EXISTS FOR (n:Requirement) ON (n.t_valid);
CREATE INDEX requirement_t_invalid IF NOT EXISTS FOR (n:Requirement) ON (n.t_invalid);
CREATE CONSTRAINT acceptancecriterion_id_unique IF NOT EXISTS FOR (n:AcceptanceCriterion) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT acceptancecriterion_source_episode_required IF NOT EXISTS FOR (n:AcceptanceCriterion) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX acceptancecriterion_lifecycle_state IF NOT EXISTS FOR (n:AcceptanceCriterion) ON (n.lifecycle_state);
CREATE INDEX acceptancecriterion_t_valid IF NOT EXISTS FOR (n:AcceptanceCriterion) ON (n.t_valid);
CREATE INDEX acceptancecriterion_t_invalid IF NOT EXISTS FOR (n:AcceptanceCriterion) ON (n.t_invalid);
CREATE CONSTRAINT constraint_id_unique IF NOT EXISTS FOR (n:Constraint) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT constraint_source_episode_required IF NOT EXISTS FOR (n:Constraint) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX constraint_lifecycle_state IF NOT EXISTS FOR (n:Constraint) ON (n.lifecycle_state);
CREATE INDEX constraint_t_valid IF NOT EXISTS FOR (n:Constraint) ON (n.t_valid);
CREATE INDEX constraint_t_invalid IF NOT EXISTS FOR (n:Constraint) ON (n.t_invalid);
CREATE CONSTRAINT businessrule_id_unique IF NOT EXISTS FOR (n:BusinessRule) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT businessrule_source_episode_required IF NOT EXISTS FOR (n:BusinessRule) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX businessrule_lifecycle_state IF NOT EXISTS FOR (n:BusinessRule) ON (n.lifecycle_state);
CREATE INDEX businessrule_t_valid IF NOT EXISTS FOR (n:BusinessRule) ON (n.t_valid);
CREATE INDEX businessrule_t_invalid IF NOT EXISTS FOR (n:BusinessRule) ON (n.t_invalid);
CREATE CONSTRAINT microrequirement_id_unique IF NOT EXISTS FOR (n:MicroRequirement) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT microrequirement_source_episode_required IF NOT EXISTS FOR (n:MicroRequirement) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX microrequirement_lifecycle_state IF NOT EXISTS FOR (n:MicroRequirement) ON (n.lifecycle_state);
CREATE INDEX microrequirement_t_valid IF NOT EXISTS FOR (n:MicroRequirement) ON (n.t_valid);
CREATE INDEX microrequirement_t_invalid IF NOT EXISTS FOR (n:MicroRequirement) ON (n.t_invalid);

// ---- Intent / Test Design layer (Session 10) ----
// Intent: the atomic, informal "what should happen" statement -- a real
// hub Transition/Requirement/AcceptanceCriterion/TestDesign all trace
// back to via TRACES_TO (schema-02). Requirement formalizes an Intent
// into EARS language; it does not replace it.
CREATE CONSTRAINT intent_id_unique IF NOT EXISTS FOR (n:Intent) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT intent_source_episode_required IF NOT EXISTS FOR (n:Intent) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX intent_lifecycle_state IF NOT EXISTS FOR (n:Intent) ON (n.lifecycle_state);
CREATE INDEX intent_t_valid IF NOT EXISTS FOR (n:Intent) ON (n.t_valid);
CREATE INDEX intent_t_invalid IF NOT EXISTS FOR (n:Intent) ON (n.t_invalid);
// TestDesign: one per Intent -- documents which AcceptanceCriterion(a) it
// COVERS, which real test-design technique(s) were used, and PRODUCES
// the resulting TestCase(s) (schema-02).
CREATE CONSTRAINT testdesign_id_unique IF NOT EXISTS FOR (n:TestDesign) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT testdesign_source_episode_required IF NOT EXISTS FOR (n:TestDesign) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX testdesign_lifecycle_state IF NOT EXISTS FOR (n:TestDesign) ON (n.lifecycle_state);
CREATE INDEX testdesign_t_valid IF NOT EXISTS FOR (n:TestDesign) ON (n.t_valid);
CREATE INDEX testdesign_t_invalid IF NOT EXISTS FOR (n:TestDesign) ON (n.t_invalid);

// ---- Behavior layer ----
CREATE CONSTRAINT state_id_unique IF NOT EXISTS FOR (n:State) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT state_source_episode_required IF NOT EXISTS FOR (n:State) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX state_lifecycle_state IF NOT EXISTS FOR (n:State) ON (n.lifecycle_state);
CREATE INDEX state_t_valid IF NOT EXISTS FOR (n:State) ON (n.t_valid);
CREATE INDEX state_t_invalid IF NOT EXISTS FOR (n:State) ON (n.t_invalid);
CREATE CONSTRAINT transition_id_unique IF NOT EXISTS FOR (n:Transition) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT transition_source_episode_required IF NOT EXISTS FOR (n:Transition) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX transition_lifecycle_state IF NOT EXISTS FOR (n:Transition) ON (n.lifecycle_state);
CREATE INDEX transition_t_valid IF NOT EXISTS FOR (n:Transition) ON (n.t_valid);
CREATE INDEX transition_t_invalid IF NOT EXISTS FOR (n:Transition) ON (n.t_invalid);
// Trigger/Guard removed as separate node types in a later session -- both
// are attributes of exactly one Transition (trigger, guard_expression
// properties), not their own entities. See docs/
// metis-ontology-specification.md for the authoritative rationale.
CREATE CONSTRAINT action_id_unique IF NOT EXISTS FOR (n:Action) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT action_source_episode_required IF NOT EXISTS FOR (n:Action) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX action_lifecycle_state IF NOT EXISTS FOR (n:Action) ON (n.lifecycle_state);
CREATE INDEX action_t_valid IF NOT EXISTS FOR (n:Action) ON (n.t_valid);
CREATE INDEX action_t_invalid IF NOT EXISTS FOR (n:Action) ON (n.t_invalid);
CREATE CONSTRAINT event_id_unique IF NOT EXISTS FOR (n:Event) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT event_source_episode_required IF NOT EXISTS FOR (n:Event) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX event_lifecycle_state IF NOT EXISTS FOR (n:Event) ON (n.lifecycle_state);
CREATE INDEX event_t_valid IF NOT EXISTS FOR (n:Event) ON (n.t_valid);
CREATE INDEX event_t_invalid IF NOT EXISTS FOR (n:Event) ON (n.t_invalid);
CREATE CONSTRAINT workflow_id_unique IF NOT EXISTS FOR (n:Workflow) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT workflow_source_episode_required IF NOT EXISTS FOR (n:Workflow) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX workflow_lifecycle_state IF NOT EXISTS FOR (n:Workflow) ON (n.lifecycle_state);
CREATE INDEX workflow_t_valid IF NOT EXISTS FOR (n:Workflow) ON (n.t_valid);
CREATE INDEX workflow_t_invalid IF NOT EXISTS FOR (n:Workflow) ON (n.t_invalid);

// ---- Architecture layer ----
CREATE CONSTRAINT service_id_unique IF NOT EXISTS FOR (n:Service) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT service_source_episode_required IF NOT EXISTS FOR (n:Service) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX service_lifecycle_state IF NOT EXISTS FOR (n:Service) ON (n.lifecycle_state);
CREATE INDEX service_t_valid IF NOT EXISTS FOR (n:Service) ON (n.t_valid);
CREATE INDEX service_t_invalid IF NOT EXISTS FOR (n:Service) ON (n.t_invalid);
CREATE CONSTRAINT api_id_unique IF NOT EXISTS FOR (n:API) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT api_source_episode_required IF NOT EXISTS FOR (n:API) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX api_lifecycle_state IF NOT EXISTS FOR (n:API) ON (n.lifecycle_state);
CREATE INDEX api_t_valid IF NOT EXISTS FOR (n:API) ON (n.t_valid);
CREATE INDEX api_t_invalid IF NOT EXISTS FOR (n:API) ON (n.t_invalid);
CREATE CONSTRAINT endpoint_id_unique IF NOT EXISTS FOR (n:Endpoint) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT endpoint_source_episode_required IF NOT EXISTS FOR (n:Endpoint) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX endpoint_lifecycle_state IF NOT EXISTS FOR (n:Endpoint) ON (n.lifecycle_state);
CREATE INDEX endpoint_t_valid IF NOT EXISTS FOR (n:Endpoint) ON (n.t_valid);
CREATE INDEX endpoint_t_invalid IF NOT EXISTS FOR (n:Endpoint) ON (n.t_invalid);
CREATE CONSTRAINT database_id_unique IF NOT EXISTS FOR (n:Database) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT database_source_episode_required IF NOT EXISTS FOR (n:Database) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX database_lifecycle_state IF NOT EXISTS FOR (n:Database) ON (n.lifecycle_state);
CREATE INDEX database_t_valid IF NOT EXISTS FOR (n:Database) ON (n.t_valid);
CREATE INDEX database_t_invalid IF NOT EXISTS FOR (n:Database) ON (n.t_invalid);
CREATE CONSTRAINT table_id_unique IF NOT EXISTS FOR (n:Table) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT table_source_episode_required IF NOT EXISTS FOR (n:Table) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX table_lifecycle_state IF NOT EXISTS FOR (n:Table) ON (n.lifecycle_state);
CREATE INDEX table_t_valid IF NOT EXISTS FOR (n:Table) ON (n.t_valid);
CREATE INDEX table_t_invalid IF NOT EXISTS FOR (n:Table) ON (n.t_invalid);
CREATE CONSTRAINT column_id_unique IF NOT EXISTS FOR (n:Column) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT column_source_episode_required IF NOT EXISTS FOR (n:Column) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX column_lifecycle_state IF NOT EXISTS FOR (n:Column) ON (n.lifecycle_state);
CREATE INDEX column_t_valid IF NOT EXISTS FOR (n:Column) ON (n.t_valid);
CREATE INDEX column_t_invalid IF NOT EXISTS FOR (n:Column) ON (n.t_invalid);
CREATE CONSTRAINT kafkatopic_id_unique IF NOT EXISTS FOR (n:KafkaTopic) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT kafkatopic_source_episode_required IF NOT EXISTS FOR (n:KafkaTopic) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX kafkatopic_lifecycle_state IF NOT EXISTS FOR (n:KafkaTopic) ON (n.lifecycle_state);
CREATE INDEX kafkatopic_t_valid IF NOT EXISTS FOR (n:KafkaTopic) ON (n.t_valid);
CREATE INDEX kafkatopic_t_invalid IF NOT EXISTS FOR (n:KafkaTopic) ON (n.t_invalid);
CREATE CONSTRAINT externalsystem_id_unique IF NOT EXISTS FOR (n:ExternalSystem) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT externalsystem_source_episode_required IF NOT EXISTS FOR (n:ExternalSystem) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX externalsystem_lifecycle_state IF NOT EXISTS FOR (n:ExternalSystem) ON (n.lifecycle_state);
CREATE INDEX externalsystem_t_valid IF NOT EXISTS FOR (n:ExternalSystem) ON (n.t_valid);
CREATE INDEX externalsystem_t_invalid IF NOT EXISTS FOR (n:ExternalSystem) ON (n.t_invalid);

// ---- Implementation layer ----
CREATE CONSTRAINT repository_id_unique IF NOT EXISTS FOR (n:Repository) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT repository_source_episode_required IF NOT EXISTS FOR (n:Repository) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX repository_lifecycle_state IF NOT EXISTS FOR (n:Repository) ON (n.lifecycle_state);
CREATE INDEX repository_t_valid IF NOT EXISTS FOR (n:Repository) ON (n.t_valid);
CREATE INDEX repository_t_invalid IF NOT EXISTS FOR (n:Repository) ON (n.t_invalid);
CREATE CONSTRAINT class_id_unique IF NOT EXISTS FOR (n:Class) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT class_source_episode_required IF NOT EXISTS FOR (n:Class) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX class_lifecycle_state IF NOT EXISTS FOR (n:Class) ON (n.lifecycle_state);
CREATE INDEX class_t_valid IF NOT EXISTS FOR (n:Class) ON (n.t_valid);
CREATE INDEX class_t_invalid IF NOT EXISTS FOR (n:Class) ON (n.t_invalid);
CREATE CONSTRAINT method_id_unique IF NOT EXISTS FOR (n:Method) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT method_source_episode_required IF NOT EXISTS FOR (n:Method) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX method_lifecycle_state IF NOT EXISTS FOR (n:Method) ON (n.lifecycle_state);
CREATE INDEX method_t_valid IF NOT EXISTS FOR (n:Method) ON (n.t_valid);
CREATE INDEX method_t_invalid IF NOT EXISTS FOR (n:Method) ON (n.t_invalid);
CREATE CONSTRAINT pullrequest_id_unique IF NOT EXISTS FOR (n:PullRequest) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT pullrequest_source_episode_required IF NOT EXISTS FOR (n:PullRequest) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX pullrequest_lifecycle_state IF NOT EXISTS FOR (n:PullRequest) ON (n.lifecycle_state);
CREATE INDEX pullrequest_t_valid IF NOT EXISTS FOR (n:PullRequest) ON (n.t_valid);
CREATE INDEX pullrequest_t_invalid IF NOT EXISTS FOR (n:PullRequest) ON (n.t_invalid);
CREATE CONSTRAINT commit_id_unique IF NOT EXISTS FOR (n:Commit) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT commit_source_episode_required IF NOT EXISTS FOR (n:Commit) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX commit_lifecycle_state IF NOT EXISTS FOR (n:Commit) ON (n.lifecycle_state);
CREATE INDEX commit_t_valid IF NOT EXISTS FOR (n:Commit) ON (n.t_valid);
CREATE INDEX commit_t_invalid IF NOT EXISTS FOR (n:Commit) ON (n.t_invalid);
CREATE CONSTRAINT branch_id_unique IF NOT EXISTS FOR (n:Branch) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT branch_source_episode_required IF NOT EXISTS FOR (n:Branch) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX branch_lifecycle_state IF NOT EXISTS FOR (n:Branch) ON (n.lifecycle_state);
CREATE INDEX branch_t_valid IF NOT EXISTS FOR (n:Branch) ON (n.t_valid);
CREATE INDEX branch_t_invalid IF NOT EXISTS FOR (n:Branch) ON (n.t_invalid);

// ---- Testing layer ----
CREATE CONSTRAINT testcase_id_unique IF NOT EXISTS FOR (n:TestCase) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT testcase_source_episode_required IF NOT EXISTS FOR (n:TestCase) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX testcase_lifecycle_state IF NOT EXISTS FOR (n:TestCase) ON (n.lifecycle_state);
CREATE INDEX testcase_t_valid IF NOT EXISTS FOR (n:TestCase) ON (n.t_valid);
CREATE INDEX testcase_t_invalid IF NOT EXISTS FOR (n:TestCase) ON (n.t_invalid);
CREATE CONSTRAINT testsuite_id_unique IF NOT EXISTS FOR (n:TestSuite) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT testsuite_source_episode_required IF NOT EXISTS FOR (n:TestSuite) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX testsuite_lifecycle_state IF NOT EXISTS FOR (n:TestSuite) ON (n.lifecycle_state);
CREATE INDEX testsuite_t_valid IF NOT EXISTS FOR (n:TestSuite) ON (n.t_valid);
CREATE INDEX testsuite_t_invalid IF NOT EXISTS FOR (n:TestSuite) ON (n.t_invalid);
CREATE CONSTRAINT automationscript_id_unique IF NOT EXISTS FOR (n:AutomationScript) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT automationscript_source_episode_required IF NOT EXISTS FOR (n:AutomationScript) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX automationscript_lifecycle_state IF NOT EXISTS FOR (n:AutomationScript) ON (n.lifecycle_state);
CREATE INDEX automationscript_t_valid IF NOT EXISTS FOR (n:AutomationScript) ON (n.t_valid);
CREATE INDEX automationscript_t_invalid IF NOT EXISTS FOR (n:AutomationScript) ON (n.t_invalid);
// Session 12: TestRun renamed to TestCycle (a cycle is the batch/container;
// per-case results now live on the new TestExecution node below -- a real
// test-management-tool shape, TestRun/Cycle -> many TestExecutions, not one
// flat status property for the whole batch).
CREATE CONSTRAINT testcycle_id_unique IF NOT EXISTS FOR (n:TestCycle) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT testcycle_source_episode_required IF NOT EXISTS FOR (n:TestCycle) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX testcycle_lifecycle_state IF NOT EXISTS FOR (n:TestCycle) ON (n.lifecycle_state);
CREATE INDEX testcycle_t_valid IF NOT EXISTS FOR (n:TestCycle) ON (n.t_valid);
CREATE INDEX testcycle_t_invalid IF NOT EXISTS FOR (n:TestCycle) ON (n.t_invalid);
// TestExecution: one real per-TestCase result within a TestCycle (id,
// source_episode_id, executed_at, result).
CREATE CONSTRAINT testexecution_id_unique IF NOT EXISTS FOR (n:TestExecution) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT testexecution_source_episode_required IF NOT EXISTS FOR (n:TestExecution) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX testexecution_lifecycle_state IF NOT EXISTS FOR (n:TestExecution) ON (n.lifecycle_state);
CREATE INDEX testexecution_t_valid IF NOT EXISTS FOR (n:TestExecution) ON (n.t_valid);
CREATE INDEX testexecution_t_invalid IF NOT EXISTS FOR (n:TestExecution) ON (n.t_invalid);
// ApplicationConfiguration: a component-version snapshot a TestExecution ran
// against (id, source_episode_id only -- the actual versions live on its
// outgoing INCLUDES_VERSION edges to real Service nodes, not node properties).
CREATE CONSTRAINT applicationconfiguration_id_unique IF NOT EXISTS FOR (n:ApplicationConfiguration) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT applicationconfiguration_source_episode_required IF NOT EXISTS FOR (n:ApplicationConfiguration) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX applicationconfiguration_lifecycle_state IF NOT EXISTS FOR (n:ApplicationConfiguration) ON (n.lifecycle_state);
CREATE INDEX applicationconfiguration_t_valid IF NOT EXISTS FOR (n:ApplicationConfiguration) ON (n.t_valid);
CREATE INDEX applicationconfiguration_t_invalid IF NOT EXISTS FOR (n:ApplicationConfiguration) ON (n.t_invalid);
CREATE CONSTRAINT defect_id_unique IF NOT EXISTS FOR (n:Defect) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT defect_source_episode_required IF NOT EXISTS FOR (n:Defect) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX defect_lifecycle_state IF NOT EXISTS FOR (n:Defect) ON (n.lifecycle_state);
CREATE INDEX defect_t_valid IF NOT EXISTS FOR (n:Defect) ON (n.t_valid);
CREATE INDEX defect_t_invalid IF NOT EXISTS FOR (n:Defect) ON (n.t_invalid);

// ---- Operations layer ----
CREATE CONSTRAINT release_id_unique IF NOT EXISTS FOR (n:Release) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT release_source_episode_required IF NOT EXISTS FOR (n:Release) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX release_lifecycle_state IF NOT EXISTS FOR (n:Release) ON (n.lifecycle_state);
CREATE INDEX release_t_valid IF NOT EXISTS FOR (n:Release) ON (n.t_valid);
CREATE INDEX release_t_invalid IF NOT EXISTS FOR (n:Release) ON (n.t_invalid);
CREATE CONSTRAINT incident_id_unique IF NOT EXISTS FOR (n:Incident) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT incident_source_episode_required IF NOT EXISTS FOR (n:Incident) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX incident_lifecycle_state IF NOT EXISTS FOR (n:Incident) ON (n.lifecycle_state);
CREATE INDEX incident_t_valid IF NOT EXISTS FOR (n:Incident) ON (n.t_valid);
CREATE INDEX incident_t_invalid IF NOT EXISTS FOR (n:Incident) ON (n.t_invalid);
CREATE CONSTRAINT alert_id_unique IF NOT EXISTS FOR (n:Alert) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT alert_source_episode_required IF NOT EXISTS FOR (n:Alert) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX alert_lifecycle_state IF NOT EXISTS FOR (n:Alert) ON (n.lifecycle_state);
CREATE INDEX alert_t_valid IF NOT EXISTS FOR (n:Alert) ON (n.t_valid);
CREATE INDEX alert_t_invalid IF NOT EXISTS FOR (n:Alert) ON (n.t_invalid);
CREATE CONSTRAINT metrics_id_unique IF NOT EXISTS FOR (n:Metrics) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT metrics_source_episode_required IF NOT EXISTS FOR (n:Metrics) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX metrics_lifecycle_state IF NOT EXISTS FOR (n:Metrics) ON (n.lifecycle_state);
CREATE INDEX metrics_t_valid IF NOT EXISTS FOR (n:Metrics) ON (n.t_valid);
CREATE INDEX metrics_t_invalid IF NOT EXISTS FOR (n:Metrics) ON (n.t_invalid);
CREATE CONSTRAINT logs_id_unique IF NOT EXISTS FOR (n:Logs) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT logs_source_episode_required IF NOT EXISTS FOR (n:Logs) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX logs_lifecycle_state IF NOT EXISTS FOR (n:Logs) ON (n.lifecycle_state);
CREATE INDEX logs_t_valid IF NOT EXISTS FOR (n:Logs) ON (n.t_valid);
CREATE INDEX logs_t_invalid IF NOT EXISTS FOR (n:Logs) ON (n.t_invalid);

// ---- AI layer ----
// Session 11, item 5: CopilotSession/Prompt/GeneratedCode/AIDecision/
// HumanReview removed by explicit user decision -- pure LLM-session/demo
// filler, zero relationships anywhere in this codebase (verified by grep
// before removal); keeping ephemeral LLM/Copilot session data in a graph
// meant to be a global, persistent source of truth is counterproductive.
// GeneratedTest stays -- metis_mcp/test_skeleton_generator.py genuinely
// uses it for REQ-METIS-BM-03 (AI-proposed test provenance until it
// converges with a real TestCase), unlike the 5 removed above.
CREATE CONSTRAINT generatedtest_id_unique IF NOT EXISTS FOR (n:GeneratedTest) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT generatedtest_source_episode_required IF NOT EXISTS FOR (n:GeneratedTest) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX generatedtest_lifecycle_state IF NOT EXISTS FOR (n:GeneratedTest) ON (n.lifecycle_state);
CREATE INDEX generatedtest_t_valid IF NOT EXISTS FOR (n:GeneratedTest) ON (n.t_valid);
CREATE INDEX generatedtest_t_invalid IF NOT EXISTS FOR (n:GeneratedTest) ON (n.t_invalid);

// ---- Governance layer ----
CREATE CONSTRAINT constitution_id_unique IF NOT EXISTS FOR (n:Constitution) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT constitution_source_episode_required IF NOT EXISTS FOR (n:Constitution) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX constitution_lifecycle_state IF NOT EXISTS FOR (n:Constitution) ON (n.lifecycle_state);
CREATE INDEX constitution_t_valid IF NOT EXISTS FOR (n:Constitution) ON (n.t_valid);
CREATE INDEX constitution_t_invalid IF NOT EXISTS FOR (n:Constitution) ON (n.t_invalid);
CREATE CONSTRAINT externalapispec_id_unique IF NOT EXISTS FOR (n:ExternalAPISpec) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT externalapispec_source_episode_required IF NOT EXISTS FOR (n:ExternalAPISpec) REQUIRE n.source_episode_id IS NOT NULL;
CREATE INDEX externalapispec_lifecycle_state IF NOT EXISTS FOR (n:ExternalAPISpec) ON (n.lifecycle_state);
CREATE INDEX externalapispec_t_valid IF NOT EXISTS FOR (n:ExternalAPISpec) ON (n.t_valid);
CREATE INDEX externalapispec_t_invalid IF NOT EXISTS FOR (n:ExternalAPISpec) ON (n.t_invalid);

// ---- Full-text index for semantic/keyword retrieval (§8.2 BM25 mode) ----
// Covers every entity with free-text fields worth searching -- extend this
// list as new text-bearing labels are added; it's a single call, cheap to redo.
CREATE FULLTEXT INDEX metis_graph_fulltext IF NOT EXISTS 
FOR (n:Requirement | AcceptanceCriterion | BusinessRule | MicroRequirement | Constitution | Defect | Incident) ON EACH [n.statement, n.description, n.text];

// ---- Vector index for semantic retrieval (§8.2, Neo4j native HNSW) ----
// Neo4j vector indexes are single-label only (unlike fulltext indexes above,
// which do support a label union) -- the original single
// "metis_graph_embedding" index spanning four labels was invalid syntax,
// never actually run before this. Split into one index per label.
CREATE VECTOR INDEX metis_graph_embedding_requirement IF NOT EXISTS
FOR (n:Requirement) ON n.embedding
OPTIONS {indexConfig: {
  `vector.dimensions`: 1536,
  `vector.similarity_function`: 'cosine'
}};
CREATE VECTOR INDEX metis_graph_embedding_ac IF NOT EXISTS
FOR (n:AcceptanceCriterion) ON n.embedding
OPTIONS {indexConfig: {
  `vector.dimensions`: 1536,
  `vector.similarity_function`: 'cosine'
}};
CREATE VECTOR INDEX metis_graph_embedding_businessrule IF NOT EXISTS
FOR (n:BusinessRule) ON n.embedding
OPTIONS {indexConfig: {
  `vector.dimensions`: 1536,
  `vector.similarity_function`: 'cosine'
}};
CREATE VECTOR INDEX metis_graph_embedding_microrequirement IF NOT EXISTS
FOR (n:MicroRequirement) ON n.embedding
OPTIONS {indexConfig: {
  `vector.dimensions`: 1536,
  `vector.similarity_function`: 'cosine'
}};

// ---- Readable names (all canonical ontology entities) ----
// Every graph node shown to a human must have a deterministic, non-empty
// display name. Raw writers derive this before the database write; these
// constraints make that invariant impossible to bypass.
CREATE CONSTRAINT goal_name_required IF NOT EXISTS FOR (n:Goal) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT capability_name_required IF NOT EXISTS FOR (n:Capability) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT epic_name_required IF NOT EXISTS FOR (n:Epic) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT feature_name_required IF NOT EXISTS FOR (n:Feature) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT requirement_name_required IF NOT EXISTS FOR (n:Requirement) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT acceptancecriterion_name_required IF NOT EXISTS FOR (n:AcceptanceCriterion) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT constraint_name_required IF NOT EXISTS FOR (n:Constraint) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT businessrule_name_required IF NOT EXISTS FOR (n:BusinessRule) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT microrequirement_name_required IF NOT EXISTS FOR (n:MicroRequirement) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT intent_name_required IF NOT EXISTS FOR (n:Intent) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT testdesign_name_required IF NOT EXISTS FOR (n:TestDesign) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT state_name_required IF NOT EXISTS FOR (n:State) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT transition_name_required IF NOT EXISTS FOR (n:Transition) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT action_name_required IF NOT EXISTS FOR (n:Action) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT event_name_required IF NOT EXISTS FOR (n:Event) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT workflow_name_required IF NOT EXISTS FOR (n:Workflow) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT service_name_required IF NOT EXISTS FOR (n:Service) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT api_name_required IF NOT EXISTS FOR (n:API) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT endpoint_name_required IF NOT EXISTS FOR (n:Endpoint) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT database_name_required IF NOT EXISTS FOR (n:Database) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT table_name_required IF NOT EXISTS FOR (n:Table) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT column_name_required IF NOT EXISTS FOR (n:Column) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT kafkatopic_name_required IF NOT EXISTS FOR (n:KafkaTopic) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT externalsystem_name_required IF NOT EXISTS FOR (n:ExternalSystem) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT repository_name_required IF NOT EXISTS FOR (n:Repository) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT class_name_required IF NOT EXISTS FOR (n:Class) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT method_name_required IF NOT EXISTS FOR (n:Method) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT pullrequest_name_required IF NOT EXISTS FOR (n:PullRequest) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT commit_name_required IF NOT EXISTS FOR (n:Commit) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT branch_name_required IF NOT EXISTS FOR (n:Branch) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT testcase_name_required IF NOT EXISTS FOR (n:TestCase) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT testsuite_name_required IF NOT EXISTS FOR (n:TestSuite) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT automationscript_name_required IF NOT EXISTS FOR (n:AutomationScript) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT testcycle_name_required IF NOT EXISTS FOR (n:TestCycle) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT testexecution_name_required IF NOT EXISTS FOR (n:TestExecution) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT applicationconfiguration_name_required IF NOT EXISTS FOR (n:ApplicationConfiguration) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT defect_name_required IF NOT EXISTS FOR (n:Defect) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT release_name_required IF NOT EXISTS FOR (n:Release) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT incident_name_required IF NOT EXISTS FOR (n:Incident) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT alert_name_required IF NOT EXISTS FOR (n:Alert) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT jiraitem_name_required IF NOT EXISTS FOR (n:JiraItem) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT metrics_name_required IF NOT EXISTS FOR (n:Metrics) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT logs_name_required IF NOT EXISTS FOR (n:Logs) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT generatedtest_name_required IF NOT EXISTS FOR (n:GeneratedTest) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT constitution_name_required IF NOT EXISTS FOR (n:Constitution) REQUIRE n.name IS NOT NULL;
CREATE CONSTRAINT externalapispec_name_required IF NOT EXISTS FOR (n:ExternalAPISpec) REQUIRE n.name IS NOT NULL;
