#!/usr/bin/env bash
# Run CI's `test` job the way GitHub runs it, before pushing.
#
# **Why this exists rather than "just run pytest".** The suite passed on a
# developer's machine and failed on CI twice in a row, for two reasons neither
# of which a local `pytest` could ever show:
#
#   1. The OS and interpreter differ. `docs/guide/cli.md` is generated by
#      capturing argparse's `--help` verbatim, and argparse's usage wrapping
#      changed in 3.13 -- so the committed guide matched a 3.13 machine and not
#      ubuntu's 3.12.
#   2. **The checkout differs.** `actions/checkout` fetches ONE commit by
#      default, so `HEAD~1` does not exist. A working tree always has history;
#      CI does not. That is invisible to every local run.
#
# So this reproduces the environment, not just the command: a Linux container,
# the pinned interpreter, and a SHALLOW CLONE at the depth CI uses.
#
# Usage:  scripts/ci-local.sh [fetch-depth]     (default 2, matching ci.yml)
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPTH="${1:-2}"
IMAGE="ghcr.io/astral-sh/uv:python3.13-bookworm-slim"

echo "==> CI 'test' job, Linux/py3.13, fetch-depth=${DEPTH}"
echo "    (uncommitted changes ARE included: the tree is overlaid onto the clone)"

docker run --rm -v "$REPO":/src:ro "$IMAGE" bash -c "
  set -e
  apt-get update -qq >/dev/null 2>&1 && apt-get install -y -qq git >/dev/null 2>&1
  git config --global --add safe.directory '*'

  git clone -q --depth ${DEPTH} file:///src /c 2>/dev/null

  # The clone carries COMMITTED state; overlay the working tree so uncommitted
  # work is what gets tested. Without this the script answers a question about
  # the last commit rather than about what you are about to push.
  tar -C /src --exclude=.git --exclude=.venv --exclude=build \
      --exclude=__pycache__ --exclude='*.egg-info' -cf - . | tar -C /c -xf -

  cd /c/metis-server
  rm -rf .venv build metis_mcp_server.egg-info
  uv venv --python 3.13 -q
  uv pip install -q -e '.[test]'

  echo '--- Test suite (engine-free half) ---'
  uv run python -m pytest -q \
    --ignore=test_extraction.py --ignore=test_recipe.py \
    --ignore=test_connectivity.py --ignore=test_data_layer.py \
    --ignore=test_data_cli.py 2>&1 | tail -3

  echo '--- Generated schema is current ---'
  uv run python -m metis_mcp.ontology.schema --write >/dev/null 2>&1
  git diff --exit-code -- schema/ >/dev/null && echo PASS || { echo FAIL; exit 1; }

  echo '--- Generated agent surfaces are current ---'
  uv run python -c 'from metis_mcp.agent_generator import write; write()' >/dev/null 2>&1
  git diff --exit-code -- ../.github/agents ../plugins/metis/agents >/dev/null \
    && echo PASS || { echo FAIL; exit 1; }
"
echo "==> done. The extraction job needs Joern and is not reproduced here;"
echo "    run it natively:  uv run python -m pytest -q test_extraction.py ..."
