"""The test design as a Markdown document people and agents edit.

**The rule, from SP-1 by way of `risk/document.py`:** the structure is
regenerated every run, the judgement belongs to whoever wrote it, and
regeneration never overwrites the second. A second run that silently deleted
every decision anybody recorded would look exactly like a successful one.

The split falls where `sections.py` already puts it -- `filled_by` is `COMPUTED`
or `HUMAN`, and the merge reads that rather than a second list:

| Regenerated | Preserved |
|---|---|
| every row, from the model | `Decision`, `Owner`, `Notes` on every table |
| the risk band, from the profile | `Obligation` (security), `Target` (performance) |
| the open questions and what their absence means | `Answer`, `Owner`, `Status` (uncertainty) |
| every heading, column and legend | any row a person added by hand |

**Hand-added rows survive.** A row whose id this run did not generate is carried
through untouched. Somebody adding a test condition Métis cannot see is doing the
thing this file exists for -- the architecture is asked, not gathered, so the
sections that depend on it are exactly where a person has most to add -- and a
regeneration that deleted it would teach people not to edit the file.

**Row ids are content-derived** (`builders.row_id`), so a decision follows the
condition it was made about rather than the position that condition happened to
occupy. An ordinal id would move every human decision one row down the moment a
transition was added.

**What this document refuses to print.** No readiness percentage and no verdict.
A design missing required inputs states what is missing where a conclusion would
go, and the status banner sits ABOVE the first section rather than below the last
-- burying `incomplete` under nine tables is how an unfinished design gets read
as a finished one.
"""
from __future__ import annotations

from datetime import datetime, timezone

from metis_mcp.design import builders, inputs, sections
from metis_mcp.document_table import (
    header,
    merge_rows,
    parse_rows,
    row,
    row_problems,
)

BANNER = (
    "<!-- Generated by `metis design`. Every column marked *yours* below is "
    "preserved across regeneration, and so is any row you add. Everything else "
    "is rewritten from the model each run. Do not renumber the ID column: it is "
    "derived from what the row is about, and it is how your edits find their way "
    "back. -->"
)

_TITLE = "# Test design"


def _heading(section: sections.Section) -> str:
    return f"## {section.ordinal}. {section.heading}"


def _ends_after(section: sections.Section) -> tuple[str, ...]:
    """Every heading that could follow this one, so a table read stops there.

    Scoped reads are not optional here: this document holds nine pipe-delimited
    tables, and reading them as one would move a decision from the levels table
    onto a security row. `document_table` states the same rule; this is where
    the boundaries come from.
    """
    ordered = sections.ordered()
    after = [s for s in ordered if s.ordinal > section.ordinal]
    return tuple([_heading(s) for s in after] + [_LEGEND_HEADING, _READING_HEADING])


_LEGEND_HEADING = "## How to read this"
_READING_HEADING = "## What this design is not"


def build(subject: str, context: builders.DesignContext, *,
          section: str = "") -> dict:
    """The document's structure, before it is rendered or merged.

    `section` narrows the build to one section, which is what
    `metis design --section` is for: a designer working on data conditions
    should not have to regenerate the journey table to see them.
    """
    wanted = ([sections.SECTIONS[section]] if section
              else list(sections.ordered()))
    completeness = inputs.completeness(gathered=context.gathered,
                                       answers=context.answers,
                                       section=section)
    silenced = inputs.unstatable(completeness["missing_required"])

    built: list[dict] = []
    for declared in wanted:
        rows = builders.builder_for(declared.builder)(context)
        built.append({
            "key": declared.key,
            "rows": rows,
            # The distinction the whole document turns on. A section whose
            # required inputs are missing could not be built; one whose inputs
            # were all supplied and produced nothing found nothing. They render
            # differently because they mean different things.
            "unstatable_because": silenced.get(declared.key, []),
        })

    return {
        "subject": subject,
        "section": section,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "sections": built,
        "completeness": completeness,
        "answers": dict(context.answers),
    }


def render_markdown(doc: dict) -> str:
    """The document. Deterministic apart from `generated_at`."""
    completeness = doc.get("completeness") or {}
    incomplete = completeness.get("status") == inputs.INCOMPLETE
    by_key = {s["key"]: s for s in doc["sections"]}

    lines: list[str] = [
        BANNER, "",
        f"{_TITLE} — {doc['subject']}", "",
        f"*Test design generated {doc['generated_at']}.*", "",
    ]

    # The status goes first, and it says so plainly. See the module docstring:
    # an unfinished design read as a finished one is the failure this ordering
    # exists to prevent.
    if incomplete:
        missing = completeness.get("missing_required") or []
        lines += [
            "> ## ⚠ Incomplete — this is not a finished test design",
            ">",
            f"> {len(missing)} required input(s) have no value: "
            f"**{', '.join(missing)}**.",
            ">",
            "> The sections below are what Métis could derive on its own. A",
            "> short section here means nobody has answered the question in",
            "> *Open questions and assumptions*, not that there is little to",
            "> test. Sections that could not be stated at all say so in place",
            "> of their rows.",
            "",
        ]
    else:
        lines += ["**Complete** — every declared input was supplied. What "
                  "follows rests on all of them, not on the half that was "
                  "reachable.", ""]

    current_group = ""
    for declared in sections.ordered():
        built = by_key.get(declared.key)
        if built is None:
            continue
        if declared.group != current_group:
            current_group = declared.group
            group = sections.group_for(current_group)
            if group is not None:
                lines += [f"# {group.heading}", "", f"*{group.purpose}.*", ""]

        lines += [_heading(declared), "", f"{declared.summary}", ""]
        lines += _render_section(declared, built)

    lines += _legend()
    return "\n".join(lines) + "\n"


def _render_section(declared: sections.Section, built: dict) -> list[str]:
    """One section: its table or its diagram, or the reason there is neither."""
    if declared.render == sections.DIAGRAM:
        return _render_diagram(declared, built)

    head, rule = header(declared.headings)
    lines = [head, rule]

    rows = built.get("rows") or []
    for record in rows:
        lines.append(row([record.get("id")]
                         + [record.get(f) for f in declared.fields]))

    because = built.get("unstatable_because") or []
    if not rows:
        # Two different emptinesses, and the ledger is the only thing that knows
        # which one this is.
        note = (f"{declared.absent_means} (waiting on: {', '.join(because)})"
                if because else declared.empty_means)
        lines.append(row(["\u2014", note] + [None] * (len(declared.columns) - 2)))

    lines.append("")
    # Only where there ARE rows. An empty section has already said this in place
    # of its rows, and saying it twice trains a reader to skip both.
    if because and rows:
        # **A section with rows AND missing inputs is the dangerous case.** It
        # looks complete -- there is a table, and the table has content -- while
        # resting on inputs nobody supplied. An empty section announces itself;
        # this one has to be told to.
        lines += [
            f"> **Partial.** Built without "
            f"{', '.join(f'`{name}`' for name in because)}. "
            f"{declared.absent_means}. What is above is what could be derived "
            f"anyway, and it is not the whole section.",
            ""]

    lines += ["**Columns.** " + "  ".join(
        f"*{column.heading}* — {column.means}"
        + (f" One of: {', '.join(column.allowed)}." if column.allowed else "")
        + (" **Yours.**" if column.filled_by == sections.HUMAN else "")
        for column in declared.columns if column.means), ""]
    return lines


def _render_diagram(declared: sections.Section, built: dict) -> list[str]:
    """A section that is a picture rather than a table.

    **Nothing here is a person's to edit**, and that is the whole reason the mode
    exists: the merge reads cells by position, so a section with no cells has
    nothing to preserve and — more importantly — nothing to lose when it is
    rewritten. A reader who annotates the diagram loses it on the next run, so
    the section says so rather than letting them find out.
    """
    rows = built.get("rows") or []
    because = built.get("unstatable_because") or []

    if not rows:
        note = (f"{declared.absent_means} (waiting on: {', '.join(because)})"
                if because else declared.empty_means)
        return [f"> {note}", ""]

    lines: list[str] = []
    for record in rows:
        diagram = record.get("diagram") or ""
        if diagram:
            lines += ["```mermaid", diagram, "```", ""]
        note = record.get("note") or ""
        if note:
            lines += [f"*{note}*", ""]

    lines += [
        "**Regenerated whole, and nothing in it is yours.** This section has no "
        "columns, so there is nothing for a regeneration to preserve — an "
        "annotation added to the diagram is lost on the next run. Put the "
        "observation in a row of the section it is about, where it survives.",
        "",
    ]
    if because:
        lines += [
            f"> **Partial.** Built without "
            f"{', '.join(f'`{name}`' for name in because)}. "
            f"{declared.absent_means}.",
            ""]
    return lines


def _legend() -> list[str]:
    return [
        _LEGEND_HEADING, "",
        "- **The ID column is a key, not a number.** It is derived from what "
        "the row is about, so your decisions stay attached to the condition "
        "you made them about when the model changes.",
        "- **Columns marked *Yours* are preserved**, and so is any row you add.",
        "- **A risk band is not a probability.** It says how much there is to "
        "get wrong, derived from the model (`derived_from: model`). Métis "
        "forecasts nothing, and this document has no probability column.",
        "- **Coverage is not correctness** (C-11). A behaviour can be fully "
        "covered and currently failing.",
        "",
        _READING_HEADING, "",
        "- **It is not a test plan.** There is no schedule, no estimate and no "
        "resourcing here.",
        "- **It states conditions, never data** (M-9). "
        "`attempts = 4` is a requirement a fixture must satisfy; producing the "
        "fixture belongs to whoever executes the test.",
        "- **It computes no readiness figure.** A design missing an "
        "architecture and one missing an optional contradiction search are "
        "not nearly-finished in the same way. One of them cannot be "
        "executed at all, and a single number would hide which.",
        "",
    ]


def parse(text: str, declared: sections.Section) -> dict[str, dict]:
    """One section's rows out of an existing document, keyed by id."""
    return parse_rows(text, heading=_heading(declared),
                      ends=_ends_after(declared), columns=declared.fields)


def parse_problems(text: str) -> list[str]:
    """Row ids, per section, that could not be read.

    Reported rather than dropped. A row somebody edited into a shape this cannot
    parse is an edit at risk, and silently discarding it is the same defect as
    overwriting it.
    """
    problems: list[str] = []
    for declared in sections.ordered():
        if declared.render == sections.DIAGRAM:
            continue
        problems += [f"{declared.key}:{rid}" for rid in row_problems(
            text, heading=_heading(declared), ends=_ends_after(declared),
            columns=declared.fields)]
    return problems


def merge(doc: dict, existing: str) -> dict:
    """`doc` with every human column and hand-added row carried over.

    The whole point of the module. Returns a NEW document: the generated
    structure, with each column a person owns restored from the file that was
    already there, and every row this run did not produce appended untouched.
    """
    if not existing.strip():
        return doc

    out = dict(doc)
    merged_sections: list[dict] = []
    carried_over: list[str] = []

    for built in doc["sections"]:
        declared = sections.SECTIONS[built["key"]]
        if declared.render == sections.DIAGRAM:
            # Nothing to merge and nothing to carry: no columns means no human
            # half. Passing it through `merge_rows` would work and would also
            # be a claim that something was preserved.
            merged_sections.append(built)
            continue
        previous = parse(existing, declared)
        merged, leftover = merge_rows(built["rows"], previous,
                                      human_columns=declared.human_columns)
        # A row this run did not generate is somebody's, or is about a fact that
        # has gone. Both are kept: Métis deciding a person's row is obsolete is
        # not a call it can make.
        carried = [{**prior, "carried": True} for prior in leftover]
        carried_over += [str(prior.get("id")) for prior in carried]
        merged_sections.append({**built, "rows": merged + carried})

    out["sections"] = merged_sections
    out["carried_over"] = carried_over
    return out


def verify(text: str) -> list[str]:
    """Structural findings about a document somebody has edited.

    **Python computes, a person or a model writes, Python verifies.** That third
    step is what makes an editable generated document safe to hand round, and it
    is the same shape `check_design_sync.py` has: a deterministic structural
    check, no model call.

    What it checks is what the merge depends on -- every section still present,
    every table still carrying its declared headings, every row still readable,
    and every closed vocabulary still holding only declared values. What it does
    NOT check is judgement: whether a decision is right, whether an owner is the
    correct one, whether a condition is worth testing. Those are the columns a
    person owns, and a checker with an opinion about them would be a checker
    people route around.
    """
    findings: list[str] = []

    for declared in sections.ordered():
        heading = _heading(declared)
        if heading not in text:
            findings.append(
                f"section `{declared.key}` is missing its heading ({heading}). "
                f"Regeneration will re-add it, and any rows you put under a "
                f"renamed heading will not be found")
            continue
        if declared.render == sections.DIAGRAM:
            # No columns, so no header line and no positional cells. The
            # heading check above is the whole of what can be verified here.
            continue
        expected, _rule = header(declared.headings)
        if expected not in text:
            findings.append(
                f"section `{declared.key}` no longer carries its declared "
                f"columns. The merge reads cells by position, so an added or "
                f"reordered column moves every edit below it")

    for problem in parse_problems(text):
        findings.append(
            f"row {problem} could not be read and would be lost on the next "
            f"regeneration — it has fewer cells than its table has columns")

    for declared in sections.ordered():
        if declared.render == sections.DIAGRAM:
            continue
        closed = {c.key: set(c.allowed) for c in declared.columns if c.allowed}
        if not closed:
            continue
        for identifier, record in parse(text, declared).items():
            for key, allowed in closed.items():
                value = record.get(key)
                if value is not None and value not in allowed:
                    findings.append(
                        f"{declared.key}:{identifier} has {key}={value!r}, "
                        f"which is not one of {', '.join(sorted(allowed))}")
    return findings
