"""
Playwright (TypeScript) from a resolved payload.

**Every locator is traceable.** A selector reaches this file only because the
source named one literally (`js-ui` extracts those) or because a person wrote it
in a fixtures file. Anything else arrives as `__unrecoverable__` and is emitted
as a TODO carrying the element hint — never as `page.getByText(<the variable
name>)`, which would look like a locator and bind to nothing.
"""
from __future__ import annotations

from metis_mcp.rendering.generators import _data
from metis_mcp.rendering.payload import UNRECOVERABLE

HEADER = """// GENERATED by `metis generate --target playwright`. Do not hand-edit:
// regenerate after the model changes, or the test and the model disagree
// silently. Values and selectors come from extracted source or from an
// authored fixtures file; anything Métis could not recover is a TODO below
// rather than a guess.
import {{ test, expect }} from '@playwright/test';

// Model:     {model_id}
// Criterion: {criterion}
"""


def _ts(value: str) -> str:
    """A TypeScript string literal. Quotes and backslashes escaped."""
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def _todo(what: str, hint: str) -> str:
    hint_text = f" — {hint}" if hint and hint != UNRECOVERABLE else ""
    return f"  // TODO({what}){hint_text}: not recovered from source and no fixture supplied"


def _step(step: dict, *, index: int) -> list[str]:
    act = step.get("act") or {}
    # The condition, not a solved value (T-9c). Comments because a precondition
    # is a fact about the WORLD, which the runner cannot assert — but the wording,
    # the anchor and the evaluation order belong in front of whoever builds the
    # fixture.
    lines: list[str] = _data.guard_lines(step, indent="  ")

    action = act.get("action")
    element = act.get("element")
    if action == UNRECOVERABLE or not action:
        lines.append(_todo(f"step {index} action", act.get("derived_from_trigger", "")))
    elif element == UNRECOVERABLE:
        lines.append(_todo(f"step {index} selector", act.get("element_hint", "")))
        lines.append(f"  // await page.{action}(<selector>);")
    else:
        lines.append(f"  await page.{action}({_ts(element)});")

    if step.get("is_assertion"):
        assertion = step.get("assert") or {}
        expected = assertion.get("expected_state")
        # The state a case lands in, always. It used to appear only inside a TODO
        # when nothing was observable, so a case that DID know what to check
        # never said where it had arrived.
        lines.append(f"  // expected state: {expected or '?'}")
        # `page` is carried unconditionally by `_assert_detail` now; a UI test
        # that does not say which page it is on has not said much.
        page = assertion.get("page") or act.get("page")
        if page:
            lines.append(f"  //   page: {page}")
        condition = assertion.get("expected_condition") or act.get("expected_condition")
        if condition:
            lines.append(f"  //   expect: {condition}")
        if assertion.get("observable") == UNRECOVERABLE:
            lines.append(_todo(f"step {index} observable",
                               f"state {expected}" if expected else ""))
    return lines


def emit(resolved: dict) -> str:
    """One Playwright test from one resolved payload."""
    payload = resolved.get("resolved", resolved)
    lines = [HEADER.format(model_id=payload.get("model_id", "?"),
                           criterion=payload.get("criterion", "?"))]

    unresolved = resolved.get("unresolved", [])
    if unresolved:
        lines.append(f"// {len(unresolved)} field(s) unrecovered — see the TODOs.")
    lines.append("")

    lines.append(f"test({_ts(payload.get('case_id', 'case'))}, async ({{ page }}) => {{")
    # See `_data`: the join supplies these and both emitters used to drop them.
    lines.extend(_data.lines(payload, indent="  "))
    for index, step in enumerate(payload.get("setup") or [], start=1):
        lines.extend(_step(step, index=index))
    act = payload.get("act")
    if act:
        lines.append("")
        lines.extend(_step(act, index=0))
    lines.append("});")
    lines.append("")
    return "\n".join(lines)
