"""
REST Assured (Java, JUnit 5) from a resolved payload.

**Nothing is asserted that was not recovered.** An expected status reaches this
file only because the transition carried one; where it did not, the assertion is
a TODO rather than `assertThat(200)`, which would pass for the wrong reason.

**One class per model, not one file per case.** Java requires a public class to
live in a file named after it, so emitting a file per case — each declaring the
same `<Model>Test` — produced sixteen files that `javac` rejects on the first
line of each. It looked like working test code and was not compilable, which is
the failure this whole module is written to avoid, arriving as syntax instead of
as a fabricated value. A JUnit "test" is a *method*; the class is the model. So
this emitter owns its file layout (`emit_files`) rather than letting the caller
name files, because the constraint is a fact about the language.
"""
from __future__ import annotations

import re
from collections.abc import Sequence

from metis_mcp.rendering.generators import _data
from metis_mcp.rendering.test_case import input_condition
from metis_mcp.rendering.payload import UNRECOVERABLE

BANNER = """// GENERATED by `metis generate --target rest-assured`. Do not hand-edit:
// regenerate after the model changes, or the test and the model disagree
// silently. Values come from extracted source or from an authored fixtures
// file; anything Métis could not recover is a TODO below rather than a guess.
import io.restassured.RestAssured;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;

// Model:     {model_id}
public class {class_name} {{
"""


def _java(value: str) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _method_name(case_id: str) -> str:
    cleaned = re.sub(r"[^0-9a-zA-Z]+", "_", str(case_id)).strip("_") or "case"
    if cleaned[0].isdigit():
        cleaned = "case_" + cleaned
    return cleaned


def class_name_for(model_id: str) -> str:
    parts = re.split(r"[^0-9a-zA-Z]+", str(model_id))
    name = "".join(p[:1].upper() + p[1:] for p in parts if p) or "Model"
    return f"{name}Test"



def _value_for(condition: str, data) -> str:
    """An authored value for this condition, where the fixtures join supplied one.

    `resolve_payload` writes `value` onto the data requirement whose `condition`
    a fixture matched. Reading it here is what makes `--fixtures` reach a request
    body rather than only a comment.
    """
    for requirement in data or ():
        if (requirement or {}).get("condition") == condition and "value" in requirement:
            return str(requirement["value"])
    return ""


def _request_body(act: dict, data, *, index: int) -> list[str]:
    """What a caller must send, as the condition it must satisfy.

    **This is why a POST used to be emitted with no body at all.** `inputs`
    reached the payload and no emitter read it, so a write with a fully recovered
    request was rendered as `given().when().post(path)` — a call that cannot
    succeed, in a file that looks finished.

    The condition, never an invented value (T-9c, M-9): the model states that the
    body is `a required RecordDto`, and which document satisfies that is a
    decision a person makes. A real `.body(...)` appears only where the fixtures
    join supplied one, and then it is labelled as authored.
    """
    body = [p for p in (act.get("inputs") or ()) if (p or {}).get("location") == "body"]
    if not body:
        return []

    lines = []
    for parameter in body:
        condition = input_condition(parameter)
        supplied = _value_for(condition, data)
        lines.append(f"            // body: {condition}")
        if supplied:
            lines.append(f"            .body({_java(supplied)})   "
                         f"// authored fixture, not recovered")
        else:
            lines.append(f"            // TODO(step {index} body): no fixture "
                         f"supplies one, and inventing a document is not a fact "
                         f"about the system")
    return lines


def _expectations(step: dict, *, index: int, status_asserted: bool) -> list[str]:
    """The target state and what can be checked about it.

    A case is a transition AND the state it lands in. Without this the file says
    what to do and never what makes it right — a reader could not tell one 200
    from another.
    """
    assertion = step.get("assert")
    if not assertion:
        return []

    lines = [f"            // expected state: {assertion.get('expected_state', '?')}"]

    for media in assertion.get("media_types") or ():
        # `produces`, so this asserts the RESPONSE content type. On the request
        # it would set one, which is a different claim.
        lines.append(f"            .contentType({_java(media)})")

    if "expected_body" in assertion:
        body = assertion["expected_body"]
        if body:
            lines.append(f"            // TODO(step {index} body): assert the "
                         f"response is {body} — the model records the type, and "
                         f"which matcher checks it is a decision about the "
                         f"framework")
        elif status_asserted:
            # An empty body is a FACT — `ResponseEntity<Void>` returns nothing —
            # and asserting it is a real check, not a missing one.
            lines.append('            .body(org.hamcrest.Matchers.emptyOrNullString())'
                         '   // no body: the endpoint declares none')
    elif assertion.get("observable") == UNRECOVERABLE:
        lines.append(f"            // TODO(step {index} validation): nothing "
                     f"observable was recovered — this case exercises the "
                     f"transition but cannot confirm it landed")
    return lines


def _step(step: dict, data=None, *, index: int) -> list[str]:
    act = step.get("act") or {}
    # The precondition, where it came from, and the order it is evaluated in.
    # This was one line carrying the joined guard string; the business wording,
    # the anchor and the check ordering were all held by the model and reached no
    # artefact.
    lines: list[str] = _data.guard_lines(step, indent="        ")

    method = act.get("method")
    path = act.get("path")
    if method == UNRECOVERABLE or path == UNRECOVERABLE:
        trigger = act.get("derived_from_trigger", "")
        lines.append(f"        // TODO(step {index} request) — {trigger}: "
                     f"method/path not recoverable from the trigger")
        # Still say where it was meant to land. Whether a call can be issued and
        # what it should land in are independent facts.
        lines.extend(_expectations(step, index=index, status_asserted=False))
        return lines

    lines.append("        given()")
    for security in act.get("security") or ():
        scheme = security.get("scheme") or security.get("type") or "auth"
        lines.append(f"            // auth required: {scheme}")
        lines.append("            // TODO: supply the credential; Métis states "
                     "the requirement, never the secret")
    lines.extend(_request_body(act, data, index=index))
    lines.append("        .when()")
    lines.append(f"            .{str(method).lower()}({_java(path)})")
    lines.append("        .then()")

    status = act.get("expected_status")
    if status is None:
        lines.append(f"            // TODO(step {index} status): the transition "
                     f"records no outcome status; asserting one would invent it")
    else:
        lines.append(f"            .statusCode({status})")
    lines.extend(_expectations(step, index=index, status_asserted=status is not None))
    lines.append("        ;")
    return lines


def _test_method(resolved: dict, *, method_name: str) -> list[str]:
    """The `@Test` method for one case, with no class around it."""
    payload = resolved.get("resolved", resolved)
    lines: list[str] = []

    lines.append(f"    // Criterion: {payload.get('criterion', '?')}")
    unresolved = resolved.get("unresolved", [])
    if unresolved:
        lines.append(f"    // {len(unresolved)} field(s) unrecovered — see the TODOs.")

    lines.append("    @Test")
    lines.append(f"    public void {method_name}() {{")
    # The conditions the case states, and any value a person authored for them.
    # Dropping these made `--fixtures` a no-op on the artefact.
    lines.extend(_data.lines(payload, indent="        "))
    data = payload.get("data_requirements")
    for index, step in enumerate(payload.get("setup") or [], start=1):
        lines.extend(_step(step, data, index=index))
    act = payload.get("act")
    if act:
        lines.append("")
        lines.extend(_step(act, data, index=0))
    lines.append("    }")
    return lines


def _unique(name: str, taken: set[str]) -> str:
    """A method name no other method in this class already has.

    Aggregating into one class made collisions possible for the first time: two
    case ids differing only in punctuation (`tc-1`, `tc_1`) sanitise to the same
    identifier, and two methods with one name is a compile error, not a warning.
    """
    if name not in taken:
        taken.add(name)
        return name
    n = 2
    while f"{name}_{n}" in taken:
        n += 1
    taken.add(f"{name}_{n}")
    return f"{name}_{n}"


def _class(model_id: str, documents: Sequence[dict]) -> str:
    taken: set[str] = set()
    lines = [BANNER.format(model_id=model_id, class_name=class_name_for(model_id))]
    for document in documents:
        payload = document.get("resolved", document)
        name = _unique(_method_name(payload.get("case_id", "case")), taken)
        lines.extend(_test_method(document, method_name=name))
        lines.append("")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def emit(resolved: dict) -> str:
    """One JUnit class holding one test method — a compilable unit on its own."""
    payload = resolved.get("resolved", resolved)
    return _class(payload.get("model_id", "model"), [resolved])


def emit_files(documents: Sequence[dict]) -> dict[str, str]:
    """`ClassName.java` -> source, one entry per model in `documents`.

    Named after the class because Java requires it. Grouped by model because a
    second class in the same package with the same name is the other half of the
    same error.
    """
    by_model: dict[str, list[dict]] = {}
    for document in documents:
        payload = document.get("resolved", document)
        by_model.setdefault(str(payload.get("model_id", "model")), []).append(document)
    return {f"{class_name_for(model_id)}.java": _class(model_id, docs)
            for model_id, docs in by_model.items()}
